<?PHP

$form = new Com_Wizard_Form();
$form->title = "Formulario Categorias";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . "/Admin/CatAdvertising");

$control = new Com_Wizard_Form_Control();
$control->name = "Name";
$control->label = "Nombre";
$control->default = $this->Name;
$control->required = true;
$control->length = 50;
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Type";
$control->label = "Tipo";
$control->default = $this->Type;
$control->required = true;
$control->addItem('1', 'Home');
$control->addItem('2', 'Lateral Izquierdo');
$control->addItem('0', 'Paginas Internas');
$form->add($control);

$control = new Com_Wizard_Form_Control_Select();
$control->name = "Status";
$control->label = "Estado";
$control->default = $this->Status;
$control->required = true;
$control->addItem('1', 'Leido');
$control->addItem('0', 'No Leido');
$form->add($control);

$form->render();
