<?PHP

$db = new Entities_Suscription();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Suscripcion ";
$grid->setIdField("SusId");
$grid->setLanField("SusLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "SusTitle" => "Nombre","SusPrice" => "Precio", "SusStatus" => "Estado"));
$grid->setFilters(array("SusTitle" => get('SusTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Suscription/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Suscription/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Suscription/Delete/id/_ID_' . "':'';");

$grid->customField("SusStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
