<section class="col-xs-12">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-12 content-header-1-title bg-bookmall">
                <h3>SUSCRIPTION</h3>
            </div>
        </div>
    </div>
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div data-slide-bg="https://k60.kn3.net/taringa/9/5/E/C/5/9/jokersegundo/F89.jpg" class="swiper-slide"
                 data-swiper-slide-index="2"
                 style="height: 550px; background-image: url(https://k60.kn3.net/taringa/9/5/E/C/5/9/jokersegundo/F89.jpg); background-size: cover;">
                <div class="swiper-slide-caption">
                    <div class="jubotron-variant-1">
                        <div data-caption-animate="fadeInUp" class="post-meta not-animated">
                            <p>
                                <time datetime="2016"><a target="_blank" href="#"> april 05, 2016</a></time>
                            </p>
                        </div>
                        <h1 data-caption-animate="fadeInUp" data-caption-delay="400" class="not-animated"><a
                                target="_blank" href="#">Descripcion</a></h1><a
                            target="_blank" href="#" data-caption-animate="fadeInUp" data-caption-delay="800"
                            class="btn btn-transparent btn-lg not-animated">Read more</a>
                    </div>
                </div>
            </div>
            <div data-slide-bg="https://k60.kn3.net/taringa/9/5/E/C/5/9/jokersegundo/F89.jpg" class="swiper-slide"
                 data-swiper-slide-index="2"
                 style="height: 550px; background-image: url(https://k60.kn3.net/taringa/9/5/E/C/5/9/jokersegundo/F89.jpg); background-size: cover;">
                <div class="swiper-slide-caption">
                    <div class="jubotron-variant-1">
                        <div data-caption-animate="fadeInUp" class="post-meta not-animated">
                            <p>
                                <time datetime="2016"><a target="_blank" href="#"> april 05, 2016</a></time>
                            </p>
                        </div>
                        <h1 data-caption-animate="fadeInUp" data-caption-delay="400" class="not-animated"><a
                                target="_blank" href="#">Descripcion</a></h1><a
                            target="_blank" href="#" data-caption-animate="fadeInUp" data-caption-delay="800"
                            class="btn btn-transparent btn-lg not-animated">Read more</a>
                    </div>
                </div>
            </div>
            <div data-slide-bg="https://k60.kn3.net/taringa/9/5/E/C/5/9/jokersegundo/F89.jpg" class="swiper-slide"
                 data-swiper-slide-index="2"
                 style="height: 550px; background-image: url(https://k60.kn3.net/taringa/9/5/E/C/5/9/jokersegundo/F89.jpg); background-size: cover;">
                <div class="swiper-slide-caption">
                    <div class="jubotron-variant-1">
                        <div data-caption-animate="fadeInUp" class="post-meta not-animated">
                            <p>
                                <time datetime="2016"><a target="_blank" href="#"> april 05, 2016</a></time>
                            </p>
                        </div>
                        <h1 data-caption-animate="fadeInUp" data-caption-delay="400" class="not-animated"><a
                                target="_blank" href="#">Descripcion</a></h1><a
                            target="_blank" href="#" data-caption-animate="fadeInUp" data-caption-delay="800"
                            class="btn btn-transparent btn-lg not-animated">Read more</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
    </div>

</section>
<div class="container-fluid content-tool bg-white">
    <h3>Suscribete a la revista impresa</h3>
    <div class="row items-suscription">
        <div data-items="2" data-sm-items="3" data-lg-items="4"
             data-loop="true"
             data-nav="true" class="owl-carousel element-groups-xs-custom">

            <?php foreach ([1, 2, 3, 4, 1, 2, 3, 4] as $var): ?>
                <div data-instafeed-item="" class="owl-item item-suscription">
                    <div class="square"
                         style="background: url(http://www.fotogramas.es/var/ezflow_site/storage/images/media/imagenes/reportajes/brujas-de-campeonato/brujas02/5427949-1-esl-ES/brujas02_ampliacion.jpg); background-size: cover ">
                    </div>
                    <div class="item-suscription-title" style="background: #FFAA33" >
                        <a href="#">Titulo</a>
                    </div>
                    <div class="item-suscription-comprar">
                        <a href="#" class="btn btn-default btn-sm pull-right ">comprar</a>
                    </div>
                </div>
            <?php endforeach ?>

        </div>
    </div>
</div>


