<section class="col-xs-12">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-12 content-header-1-title bg-bookmall">
                <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtSuscripcion")->TxtDescription ?></h3>
            </div>
        </div>
    </div>
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <?php SlideShowsSuscription_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>           
        </div>
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
    </div>

</section>
<div class="container-fluid content-tool bg-white">
    <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtSuscribete")->TxtDescription ?></h3>
    <div class="row items-suscription">
        <div data-items="2" data-sm-items="3" data-lg-items="4"
             data-loop="true"
             data-nav="true" class="owl-carousel element-groups-xs-custom">

             <?php Suscription_Widget_List::getInstance()->setLan($this->lan)->render(); ?>  

        </div>
    </div>
</div>


