<div class="col-xs-12 col-md-8">
    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-3 content-header-1-title bg-note-event">
                <h3>Eventos</h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool">
                <a class="header-link"
                   href="#">Social Media S.</a>
                <a class="header-link"
                   href="#">EXMA</a>
                <a class="header-link"
                   href="#">TrendShopper</a>
                <a class="header-link"
                   href="#">Festival el Locoto</a>
            </div>
        </div>
    </div>
    <section>
        <div data-slide-bg="http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg"
             class="swiper-slide" data-swiper-slide-index="1"
             style="height: 550px; background-image: url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg); background-size: cover;">
            <div class="pull-bottom">
                <a href="#" class="tag bg-note-red">Event</a>
                <h3>Nota</h3>
                <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
            </div>
        </div>
    </section>
    <div class="container-fluid  content-tool bg-white">
        <div class="row event-body text-left">
            <p>
                Lipsum is a free and useful Lorem Ipsum generator that you can make use of in your projects. As a
                freelance designer, you might already be aware of the value of the Lorem Ipsum text. Even though it is
                centuries old, Lorem Ipsum is still very popular as a placeholder text to help designers showcase their
                designs to clients. Such placeholder text aids in visualization.
            <ul class="list-unstyled">
                <li><strong>Lugar:</strong> algun lugar</li>
                <li><strong>Lugar:</strong> algun lugar</li>
                <li><strong>Lugar:</strong> algun lugar</li>
                <li><strong>Lugar:</strong> algun lugar</li>
                <li><strong>Lugar:</strong> algun lugar</li>
            </ul>
            </p>
            <div class="col-ms-12">
                <p>
                    <iframe width="100%" height="350" src="https://www.youtube.com/embed/gbug3zTm3Ws" frameborder="0"
                            allowfullscreen></iframe>
                </p>
            </div>
            <div class="col-sm-offset-3 col-sm-6">
                <a href="#" class="content-social-link"> <i class="fa fa-twitter"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-facebook"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-instagram"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-youtube"></i></a>
            </div>
        </div>
    </div>
    <div class="container-fluid content-tool bg-white" style="margin-top: 20px">
        <div class="row">
            <div class="fb-comments"
                 data-href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "article/" . $this->note->NotId); ?>"
                 data-numposts="15"></div>
        </div>
    </div>
    <div class="container-fluid content-tool notas-items events-container">
        <div class="row">
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-12" style="padding: 0">
                <?php Advertising_Widget_Ad::getInstance()->setType('F')->setLimit(1)->renderF(); ?>
            </div>
        </div>
    </div>
</div>