<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-3 content-header-1-title bg-note-event">
                <h3>Eventos</h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool">
                <?php foreach ($this->category as $new) { ?>
                    <a class="header-link"
                       href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "events/" . $new->CatId); ?>"><?= $new->CatName; ?></a>
                   <?php } ?>
            </div>
        </div>
    </div>
    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShowsEvents_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool notas-items events-container">
        <div class="row">
            <?php foreach ($this->events as $new) { ?>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(255,255,0, 0.50) 0%,rgba(255,255,0,0.5) 100%) , url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $new->EveImage; ?>);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red"><?= CatEvents_Helper_Category::getInstance()->getId($this->lan, $new->EveCatId)->CatName; ?></a>
                        <h3><?PHP echo $new->EveTitle; ?></h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <?php } ?>
            
            <div class="col-xs-12" style="padding: 0">
                <?php Advertising_Widget_Ad::getInstance()->setType('F')->setLimit(1)->renderF(); ?>
            </div>
            <div class="col-md-12 notas-item">
                <?php Events_Widget_Important::getInstance()->setLan($this->lan)->setLimit(1)->render(); ?>
            </div>
            <?php Events_Widget_Recientes::getInstance()->setLan($this->lan)->setLimit(6)->render(); ?>
            
            
            
            
        </div>
    </div>
</div>