<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-3 content-header-1-title bg-note-event">
                <h3>Eventos</h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool">
                <a class="header-link"
                   href="#">Social Media S.</a>
                <a class="header-link"
                   href="#">EXMA</a>
                <a class="header-link"
                   href="#">TrendShopper</a>
                <a class="header-link"
                   href="#">Festival el Locoto</a>
            </div>
        </div>
    </div>
    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">

                <div
                    data-slide-bg="http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg"
                    class="swiper-slide" data-swiper-slide-index="1"
                    style="height: 550px; background-image: url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg); background-size: cover;">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
                <div
                    data-slide-bg="http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg"
                    class="swiper-slide" data-swiper-slide-index="1"
                    style="height: 550px; background-image: url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg); background-size: cover;">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
                <div
                    data-slide-bg="http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg"
                    class="swiper-slide" data-swiper-slide-index="1"
                    style="height: 550px; background-image: url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg); background-size: cover;">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>


            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool notas-items events-container">
        <div class="row">
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(255,255,0, 0.50) 0%,rgba(255,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(255,255,0, 0.50) 0%,rgba(255,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(255,255,0, 0.50) 0%,rgba(255,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(255,255,0, 0.50) 0%,rgba(255,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-xs-12" style="padding: 0">
                <?php Advertising_Widget_Ad::getInstance()->setType('F')->setLimit(1)->renderF(); ?>
            </div>
            <div class="col-md-12 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(255,0,0, 0.50) 0%,rgba(255,0,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
            <div class="col-md-6 notas-item">
                <div class="square"
                     style="background-image: linear-gradient(to bottom, rgba(0,255,0, 0.50) 0%,rgba(0,255,0,0.5) 100%) , url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50824.jpg);background-size:cover ">
                    <div class="pull-bottom">
                        <a href="#" class="tag bg-note-red">Event</a>
                        <h3>Nota</h3>
                        <span><i style="margin-right: 5px" class="fa fa-user"></i>usuario</span>
                        <span><i style="margin-right: 5px" class="fa fa-calendar"></i>fecha</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>