<?PHP 
$form=new Com_Wizard_Form();
$form->title="Formulario Cliente";

$form->addAction("floppy-disk", "Guardar", null, "document.getElementById('saveForm').click();");
$form->addAction("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase."/Admin/Clients");

$control=new Com_Wizard_Form_Control();
$control->name="Name";
$control->label="Nombre";
$control->default=$this->Name;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control_Date();
$control->name="Nacimiento";
$control->label="Fecha de Nacimiento";
$control->default=$this->Nacimiento;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control_Select();
$control->name="Gender";
$control->label="Genero";
$control->default=$this->Gender;
$control->required=true;
$control->addItem('Femenino', 'Femenino');
$control->addItem('Masculino', 'Masculino');

$form->add($control);

$control=new Com_Wizard_Form_Control();
$control->name="Email";
$control->label="Correo Electronico";
$control->default=$this->Email;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control();
$control->name="Country";
$control->label="Pais";
$control->default=$this->Country;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control();
$control->name="City";
$control->label="Ciudad";
$control->default=$this->City;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control();
$control->name="Password";
$control->label="Contraseña";
$control->default=$this->Password;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control();
$control->name="Facebook";
$control->label="Facebook";
$control->default=$this->Facebook;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control();
$control->name="Phone";
$control->label="Tel&eacute;fono";
$control->default=$this->Phone;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control_Text();
$control->name="Type";
$control->label="Tipo";
$control->default=$this->Type;
$form->add($control);

$control=new Com_Wizard_Form_Control_Date();
$control->name="Date";
$control->label="Fecha de Registro";
$control->default=$this->Date;
$control->required=true;
$control->length=50;
$form->add($control);

$control=new Com_Wizard_Form_Control_Select();
$control->name="Status";
$control->label="Estado";
$control->default=$this->Status;
$control->required=true;
$control->addItem('1', 'Publicado');
$control->addItem('0', 'No Publicado');

$form->add($control);

$form->render();