<?PHP
$db=new Entities_Venta();
$grid=new Com_Wizard_Grid();
$grid->title="Listado ventas";
$grid->setIdField("VenId");
$grid->setQuery($db->getList());
$grid->setAlias(array("VenId"=>"#Venta","VenDate"=>"fecha","VenTotal"=>"Total","VenStatus"=>"Estado"));
$grid->setFilters(array("VenId"=>get('VenId')));

$toolBar=new Com_Wizard_ToolBar();
$toolBar->add("search", "Filtrar",null,"showHide('.filters')");
$toolBar->add("log-out", "Volver",Com_Helper_Url::getInstance()->urlBase.'/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase.'/Admin/Clients/EditVenta/id/_ID_');
$grid->addAction("trash", "Eliminar", null,"confirm('Esta seguro de eliminar el registro?')?location.href='".Com_Helper_Url::getInstance()->urlBase.'/Admin/Clients/Delete/id/_ID_'."':'';");
$grid->addAction("list-alt", "Detalle", Com_Helper_Url::getInstance()->urlBase.'/Admin/Clients/DetVenta/id/_ID_');

$grid->customField("CliHasVote", array("value"=>array('1'=>'Si','0'=>'No')));

$grid->customField("VenStatus", array("value"=>array('1'=>'Pendiente','0'=>'Finalizado')));

$grid->render();