<div class="formulario">
    <div class="title">
        <h2>Dashboard</h2>

    </div>
</div>
<div class="clear"></div>
<div class="dashboard">
    <div class="icons">
        <div id="main-wrapper">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p class="counter"><?= Tracking_Model_Tracking::getInstance()->count()[0]->number; ?></p>
                                <span class="info-box-title">Visitas x mes</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-users"></i>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p class="counter"><?= Tracking_Model_Tracking::getInstance()->countUnique()[0]->number; ?></p>
                                <span class="info-box-title">Visitas unicas x mes</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-eye"></i>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p><span class="counter"><?= Clients_Model_Venta::getInstance()->getListCarritoFinalizados()[0]->number; ?></span></p>
                                <span class="info-box-title">Ventas realizadas</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-basket"></i>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel info-box panel-white">
                        <div class="panel-body">
                            <div class="info-box-stats">
                                <p class="counter"><?= Contact_Model_Contact::getInstance()->countAll()[0]->number; ?></p>
                                <span class="info-box-title">Mesajes recibidos</span>
                            </div>
                            <div class="info-box-icon">
                                <i class="icon-envelope"></i>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- Row -->
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h4 class="panel-title">Compras realizadas</h4>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive project-stats">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Cliente</th>
                                            <th>Estado</th>
                                            <th>Fecha</th>
                                            <th>Total</th>
                                            <th>Ver Detalle</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $list = Clients_Model_Venta::getInstance()->getListCarritoAll();
                                        foreach ($list as $obj) {
                                            ?>
                                            <tr>
                                                <th scope="row"><?= $obj->VenId ?></th>
                                                <td><?= Clients_Model_Client::getInstance()->get($obj->VenCliId)->CliName; ?></td>
                                                <?php if ($obj->VenStatus == '0') { ?>
                                                    <td><span class="label label-success">Finalizado</span></td>
                                                <?php } else { ?>  
                                                    <td><span class="label label-info">Pendiente</span></td>
    <?php } ?>    
                                                <td><?= $obj->VenDate ?></td>
                                                <td><?= $obj->VenTotal ?></td>
                                                <td>                            
                                                    <a href="<?= Com_Helper_Url::getInstance()->urlBase . '/Admin/Clients/DetVenta/id/' . $obj->VenId; ?>" type="button" class="btn btn-success btn-rounded"> <i class="icon-list"></i></a>
                                                    <a href="<?= Com_Helper_Url::getInstance()->urlBase . '/Admin/Clients/DetCompra/id/' . $obj->VenId; ?>" type="button" class="btn btn-info btn-rounded"> <i class="icon-user"></i></a>
                                                </td>
                                            </tr>
<?php } ?>    


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h4 class="panel-title">Bandeja de Entrada</h4>    
                            <div class="panel-control">
                                <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Reload"
                                   class="panel-reload"><i class="icon-reload"></i></a>
                            </div>
                        </div>
                        <div class="panel-body">

                            <div class="table-responsive project-stats">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>De</th>
                                            <th>Email</th>
                                            <th>Fecha</th>
                                            <th>Estado</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php foreach ($this->mensajes as $obj) { ?>                        
                                            <tr>
                                                <th scope="row"><?= $obj->ConId; ?></th>
                                                <td><?= $obj->ConName; ?></td>
                                                <td><?= $obj->ConEmail; ?></td>
                                                <td><?= $obj->ConDate; ?></td>
                                                <?php if ($obj->ConStatus == '0') { ?>
                                                    <td><span class="label label-success">Leido</span></td>
                                                <?php } else { ?>  
                                                    <td><span class="label label-info">No Leido</span></td>
                                                     <?php } ?> 
                                                <td>                                                   
                                                    <a href="<?= Com_Helper_Url::getInstance()->urlBase . '/Admin/Contact/Edit/lan/7/id/' . $obj->ConId; ?>" type="button" class="btn btn-info btn-rounded"> <i class="icon-envelope"></i></a>
                                                    <a href="<?= Com_Helper_Url::getInstance()->urlBase . '/Admin/Contact/Delete/id/' . $obj->ConId; ?>" type="button" class="btn btn-danger btn-rounded"> <i class="icon-trash"></i></a>                                                   
                                                </td>
                                            </tr>
                                        <?php } ?>     

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h4 class="panel-title">Weather</h4>

                            <div class="panel-control">
                                <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Reload"
                                   class="panel-reload"><i class="icon-reload"></i></a>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="weather-widget">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="weather-top">
                                            <div class="weather-current pull-left">
                                                <i class="wi wi-day-cloudy weather-icon"></i>

                                                <p><span>83<sup>&deg;F</sup></span></p>
                                            </div>
                                            <h2 class="weather-day pull-right">Miami, FL<br>
                                                <small><b>13th April, 2015</b></small>
                                            </h2>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <ul class="list-unstyled weather-info">
                                            <li>Wind <span class="pull-right"><b>ESE 16 mph</b></span></li>
                                            <li>Humidity <span class="pull-right"><b>64%</b></span></li>
                                            <li>Pressure <span class="pull-right"><b>30.15 in</b></span></li>
                                            <li>UV Index <span class="pull-right"><b>6</b></span></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-6">
                                        <ul class="list-unstyled weather-info">
                                            <li>Cloud Cover <span class="pull-right"><b>60%</b></span></li>
                                            <li>Ceiling <span class="pull-right"><b>17800 ft</b></span></li>
                                            <li>Dew Point <span class="pull-right"><b>70° F</b></span></li>
                                            <li>Visibility <span class="pull-right"><b>10 mi</b></span></li>
                                        </ul>
                                    </div>
                                    <div class="col-md-12">
                                        <ul class="list-unstyled weather-days row">
                                            <li class="col-xs-4 col-sm-2"><span>12:00</span><i
                                                    class="wi wi-day-cloudy"></i><span>82<sup>&deg;F</sup></span></li>
                                            <li class="col-xs-4 col-sm-2"><span>13:00</span><i
                                                    class="wi wi-day-cloudy"></i><span>82<sup>&deg;F</sup></span></li>
                                            <li class="col-xs-4 col-sm-2"><span>14:00</span><i
                                                    class="wi wi-day-cloudy"></i><span>82<sup>&deg;F</sup></span></li>
                                            <li class="col-xs-4 col-sm-2"><span>15:00</span><i
                                                    class="wi wi-day-cloudy"></i><span>83<sup>&deg;F</sup></span></li>
                                            <li class="col-xs-4 col-sm-2"><span>16:00</span><i
                                                    class="wi wi-day-cloudy"></i><span>82<sup>&deg;F</sup></span></li>
                                            <li class="col-xs-4 col-sm-2"><span>17:00</span><i
                                                    class="wi wi-day-sunny-overcast"></i><span>82<sup>&deg;F</sup></span></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="panel panel-white">
                        <div class="panel-heading">
                            <h4 class="panel-title">Inbox</h4>

                            <div class="panel-control">
                                <a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Reload"
                                   class="panel-reload"><i class="icon-reload"></i></a>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="inbox-widget slimscroll">
                                <a href="#">
                                    <div class="inbox-item">
                                        <div class="inbox-item-img"><img src="assets/images/avatar2.png" class="img-circle" alt="">
                                        </div>
                                        <p class="inbox-item-author">Sandra Smith</p>

                                        <p class="inbox-item-text">Hey! I'm working on your...</p>

                                        <p class="inbox-item-date">13:40 PM</p>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="inbox-item">
                                        <div class="inbox-item-img"><img src="assets/images/avatar3.png" class="img-circle" alt="">
                                        </div>
                                        <p class="inbox-item-author">Christopher</p>

                                        <p class="inbox-item-text">I've finished it! See you so...</p>

                                        <p class="inbox-item-date">13:34 PM</p>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="inbox-item">
                                        <div class="inbox-item-img"><img src="assets/images/avatar4.png" class="img-circle" alt="">
                                        </div>
                                        <p class="inbox-item-author">Amily Lee</p>

                                        <p class="inbox-item-text">This theme is awesome!</p>

                                        <p class="inbox-item-date">13:17 PM</p>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="inbox-item">
                                        <div class="inbox-item-img"><img src="assets/images/avatar5.png" class="img-circle" alt="">
                                        </div>
                                        <p class="inbox-item-author">Nick Doe</p>

                                        <p class="inbox-item-text">Nice to meet you</p>

                                        <p class="inbox-item-date">12:20 PM</p>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="inbox-item">
                                        <div class="inbox-item-img"><img src="assets/images/avatar2.png" class="img-circle" alt="">
                                        </div>
                                        <p class="inbox-item-author">Sandra Smith</p>

                                        <p class="inbox-item-text">Hey! I'm working on your...</p>

                                        <p class="inbox-item-date">10:15 AM</p>
                                    </div>
                                </a>
                                <a href="#">
                                    <div class="inbox-item">
                                        <div class="inbox-item-img"><img src="assets/images/avatar4.png" class="img-circle" alt="">
                                        </div>
                                        <p class="inbox-item-author">Amily Lee</p>

                                        <p class="inbox-item-text">This theme is awesome!</p>

                                        <p class="inbox-item-date">9:56 AM</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel twitter-box">
                        <div class="panel-body">
                            <div class="live-tile" data-mode="flip" data-speed="750" data-delay="3000">
                                <span class="tile-title pull-right">New Tweets</span>
                                <i class="fa fa-twitter"></i>

                                <div><h2 class="no-m">It’s kind of fun to do the impossible...</h2><span class="tile-date">10 April, 2015</span>
                                </div>
                                <div><h2 class="no-m">Sometimes by losing a battle you find a new way to win the war...</h2><span
                                        class="tile-date">6 April, 2015</span></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel facebook-box">
                        <div class="panel-body">
                            <div class="live-tile" data-mode="carousel" data-direction="horizontal" data-speed="750" data-delay="4500">
                                <span class="tile-title pull-right">Facebook Feed</span>
                                <i class="fa fa-facebook"></i>

                                <div><h2 class="no-m">If you're going through hell, keep going...</h2><span class="tile-date">23 March, 2015</span>
                                </div>
                                <div><h2 class="no-m">To improve is to change; to be perfect is to change often...</h2><span
                                        class="tile-date">15 March, 2015</span></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Wrapper -->

        <div class="clear"></div>
    </div>
    <div class="clear"></div>

</div>