<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-4 content-header-1-title bg-pink-notas">
                <h3><?= Categories_Helper_Category::getInstance()->getId($this->lan,$this->categoryId)->CatAlias;?></h3>
            </div>
            <div class="col-sm-8 content-header-1-options bg-blue-dark-tool">
                <?php foreach ($this->category as $new) { ?>
                    <a class="header-link" href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "notes/" . $new->CatId); ?>"><?= $new->CatAlias; ?></a>             
                <?php } ?>
            </div>
        </div>
    </div>

    <div class="container-fluid content-tool notas-items">
        <div class="row">
            <?php foreach ($this->notes as $new) { ?>
                <div class="col-md-6 notas-item">
                    <div class="square"
                         style="background-image: linear-gradient(to bottom, rgba(255, 0, 0, 0.50) 0%,rgba(255,0,0,0.5) 100%) , url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $new->NotImage; ?>);background-size:cover ">
                        <div class="square square-hover bg-white">
                            <div class="content">
                                <a href="blog_post.html" class="tag bg-shamrock"><?= Categories_Helper_Category::getInstance()->getId($this->lan, $new->NotCatId)->CatAlias; ?></a>
                                <h3><?= $new->NotTitle; ?></h3>
                                <p>
                                    <?= $new->NotResume; ?>
                                </p>
                            </div>
                        </div>
                    </div>
                    <h3><?= $new->NotTitle; ?></h3>
                    <span><i class="fa fa-calendar"></i><?= $new->NotDate; ?></span>
                </div>
            <?php } ?>
        </div>
        <div class="row hidden">
            <a href="#" style="color: white">
                <span>Cargar mas</span>
                <span class="go-down">
                    <i class="fa fa-angle-down icon-white"></i>
                </span>
            </a>
        </div>
    </div>
</div>