<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-4 content-header-1-title <?= $this->color; ?>">
                <h3><?= Categories_Helper_Category::getInstance()->getId($this->lan, $this->categoryId)->CatAlias; ?></h3>
            </div>
            <div class="col-sm-8 content-header-1-options bg-blue-dark-tool">
                <?php foreach ($this->category as $new) { ?>
                    <a class="header-link"
                       href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "notes/" . $new->CatId); ?>"><?= $new->CatAlias; ?></a>
                   <?php } ?>
            </div>
        </div>
    </div>
    <div class="container-fluid notas-header">
        <h3>
            <?= $this->note->NotTitle; ?>
        </h3>
        <span><i style="margin-right: 5px" class="fa fa-user"></i><?= $this->note->NotUser; ?></span>
        <span><i style="margin-right: 5px" class="fa fa-calendar"></i><?= $this->note->NotDate; ?></span>
    </div>
    <section>
        <!-- Swiper-->
        <!-- Slider main container -->

        <div class="swiper-container">
            <div class="swiper-wrapper">

                <div
                    data-slide-bg="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->note->NotImage; ?>"
                    class="swiper-slide" data-swiper-slide-index="1"
                    style="height: 550px; background-image: url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->note->NotImage; ?>); background-size: cover;">

                </div>


            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool bg-white">
        <div class="row text-left content-note">
            <div class="col-sm-12 ">
                <!--aqui contenido-->
                <p><?= $this->note->NotDescription; ?></p>
                <!--hasta aqui el contenido-->
            </div>
        </div>
        <form id="searchForm" method="POST" action="http://localhost/mkt/mkt//es/post/" onsubmit="">
            <input type="hidden" name="page" id="page" value="7">
        </form>
        <div class="row">
            <div class="col-sm-3 notas-back-button" style="">
                <?php $notIda = $this->note->NotId - 1; ?>
                <a onclick="changePage(<?= $notIda; ?>);"><i
                        class="fa fa-arrow-left"></i> <?= Texts_Helper_Text::getInstance()->get($this->lan, "txtAnterior")->TxtDescription ?>
                </a>
            </div>
            <div class="col-sm-3 notas-next-button" style="">
                <?php $notIdb = $this->note->NotId + 1; ?>
                <a onclick="changePage(<?= $notIdb; ?>);"> <?= Texts_Helper_Text::getInstance()->get($this->lan, "txtSiguiente")->TxtDescription ?>
                    <i class="fa fa-arrow-right"></i></a>
            </div>
            <div class="col-sm-6">
                <div class="social-container" style="margin:0;">
                    <div class="addthis_inline_share_toolbox hidden"
                         data-url="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "/article/" . $this->note->NotId); ?>"
                         data-title="<?= $this->note->NotTitle; ?>"
                         data-media="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $this->note->NotImage; ?>"></div>
                    <div class="addthis_inline_share_toolbox"></div>
                </div>
            </div>
        </div>

    </div>


    <h4 style="color:white;font-size: 22px; margin:25px 0 10px">Comentarios:</h4>
    <div class="container-fluid content-tool bg-white" style="margin-top: 20px">
        <div class="row">
            <div class="fb-comments"
                 data-href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "article/" . $this->note->NotId); ?>"
                 data-numposts="15"></div>
        </div>
    </div>
</div>


<script>

    function changePage(page) {
        $('#page').val(page);
        $('#searchForm').submit();
    }

</script>

<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-582dd089d1d08717"></script> 
