<section class="col-xs-12">
    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-12 content-header-1-title bg-bookmall">
                <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtBookMall")->TxtDescription ?></h3>
            </div>
        </div>
    </div>
</section>
<section class="col-xs-12">
    <div class="container-fluid">
        <div class="row bg-white bookmall-detail">
            <div class="col-sm-6">
                <div id="book-image" class="square"
                     style="background-image:url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?= $this->list->BooImage; ?>);background-size:cover ">
                </div>
                <div data-items="2" data-sm-items="3" data-lg-items="4"
                     data-loop="true"
                     data-nav="true" class="owl-carousel element-groups-xs-custom">
                         <?php foreach ($this->images as $new) { ?>
                        <div data-instafeed-item="" class="owl-item insta-item">
                            <a href="javascript:void(0)"
                               id="thumb-<?= $new->MedId; ?>"
                               rel="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?= $new->MedImage; ?>"
                               onclick="setImage(<?= $new->MedId; ?>)"
                               class="img-thumbnail-variant-3">
                                <div class="square"
                                     style="background: url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?= $new->MedImage; ?>); background-size: cover">
                                </div>
                            </a>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div class="col-sm-6">
                <h4><?= $this->list->BooTitle; ?></h4>
                <p class="bookmall-autor">AUTOR: <strong><?= $this->list->BooAuthor; ?></strong></p>
                <?= $this->list->BooContent; ?>

                <div class="pull-right" style="clear: both;margin: 10px 0">PRECIO: <strong
                        class="color-purple">Bs. <?= $this->list->BooPrice; ?></strong></div>

                <div class="pull-right" style="clear: both;margin: 10px 0">
                    <ul class="list-inline">
                        <li>
                            <a target="_blank" href="http://www.facebook.com/sharer.php?u=[post-url]"
                               class="icon icon-md icon-gray fa fa-facebook"></a>
                        </li>
                        <li>
                            <a target="_blank"
                               href="https://twitter.com/share?url=[post-url]&text=[post-title]&via=[via]&hashtags=[hashtags]"
                               class="icon icon-md icon-gray fa fa-twitter"></a>
                        </li>
                        <li>
                            <a target="_blank" href="https://plus.google.com/share?url=[post-url]"
                               class="icon icon-md icon-gray fa fa-google-plus"></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-12" style="height: 2px; background: #999999"></div>
            <div class="col-md-12">                
                <a onclick="SaveVenta();" class="btn btn-flat pull-right btn-primary" style="margin-right: 10px"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtAddCarrito")->TxtDescription ?></a>
            </div>
        </div>
    </div>
    <!--    aqui deberia empezar el widget de carrito-->
    <div class="container-fluid carrito bg-white">
        <div class="row">
            <div class="col-md-offset-1 col-md-10">
                <h3 style="margin-bottom: 0px">Tu pedido</h3>
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>Producto</th>
                            <th>Precio</th>
                            <th>Cantidad</th>
                            <th>TOTAL</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->carrito as $car) { ?>
                            <tr>
                        <form id="detalleForm">                                  
                            <td><a onclick="DeleteDetalle(<?= $car->DetId; ?>);" type="button"><i class="delete-item fa fa-close"></i></a></td>
                            <td><img
                                    src="http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50944_big.jpg"
                                    alt=""></td>
                            <td><?= $car->DetItem; ?></td>
                            <td>Bs. <?= $car->DetPrecio; ?></td>
                            <td>
                                <input type="hidden" name="id" value="<?= $car->DetCant; ?>">
                                <input type="number" name="value" value="1">
                            </td>
                            <td>Bs. <?= $car->DetPrecio; ?></td>
                        </form>
                        </tr>
                    <?php } ?>                     

                    </tbody>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>Total</td>
                            <td>Bs. <?= $this->Sumcarrito; ?></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <form action="#" method="post">
                <div class="col-md-offset-1 col-md-5">
                    <h3>Detalle de compra</h3>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nombre">Nombre completo</label>
                                <input type="text" class="form-control" id="nombre" placeholder="nombre">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="apellido">Apellido completo</label>
                                <input type="text" class="form-control" id="apellido" placeholder="apellido">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="cedula">Cedula</label>
                        <input type="text" class="form-control" id="cedula" placeholder="cedula">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Direccion de email</label>
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Celular</label>
                                <input type="text" class="form-control" id="celular" placeholder="celular">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pais">Pais</label>
                        <input type="text" class="form-control" id="pais" placeholder="pais">
                    </div>
                    <div class="form-group">
                        <label for="direccion">Direccion</label>
                        <input type="text" class="form-control" id="direccion1" placeholder="direccion 1">
                        <input type="text" class="form-control" id="direccion2" placeholder="direccion 2">
                    </div>
                    <div class="form-group">
                        <label for="localidad">Localidad/Ciudad</label>
                        <input type="text" class="form-control" id="localidad" placeholder="localidad">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Estado / Pais</label>
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Codigo postal / Zip</label>
                                <input type="text" class="form-control" id="celular" placeholder="celular">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <h3>Detalle de compra</h3>
                    <div class="form-group">
                        <label for="direccion">Direccion</label>
                        <input type="text" class="form-control" id="direccion1" placeholder="direccion 1">
                        <input type="text" class="form-control" id="direccion2" placeholder="direccion 2">
                    </div>
                    <div class="form-group">
                        <label for="localidad">Localidad/Ciudad</label>
                        <input type="text" class="form-control" id="localidad" placeholder="localidad">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Estado / Pais</label>
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Codigo postal / Zip</label>
                                <input type="text" class="form-control" id="celular" placeholder="celular">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripcion</label>
                        <input type="text" class="form-control" id="descripcion" placeholder="descripcion">
                    </div>
                </div>
            </form>
            <div class="col-md-10 col-md-offset-1">
                <div class="row bg-gray-ligth" style="padding: 15px;">
                    <div class="col-md-4">
                        Seleccione el metodo de pago
                    </div>
                    <div class="col-md-8">
                        <input
                            type="radio" name="emotion"
                            id="tarjeta" class="input-hidden"/>
                        <label for="tarjeta">
                            <img class="pay-method"
                                 src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/tarjeta.png"
                                 alt="tarjeta"/>
                        </label>

                        <input
                            type="radio" name="emotion"
                            id="cheque" class="input-hidden"/>
                        <label for="cheque">
                            <img class="pay-method"
                                 src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/cheque.png"
                                 alt="cheque"/>
                        </label>

                        <input
                            type="radio" name="emotion"
                            id="deposito" class="input-hidden"/>
                        <label for="deposito">
                            <img class="pay-method"
                                 src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/banco.png"
                                 alt="deposito"/>
                        </label>
                    </div>
                    <div class="col-md-12 bg-gray-dark">
                        <p>Politicas de privacidad de pago</p>

                    </div>
                    <div class="col-md-12 text-right" style="padding: 0px; margin: 15px 0">
                        <a href="#" class="btn btn-warning"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtComprar")->TxtDescription ?></a>
                    </div>

                </div>
                <br>
            </div>
        </div>
    </div>
</section>

<form id="CarritoForm">    
    <input id="cliId" name="cliId" type="text" autocomplete="off" value="<?= $this->client->CliId; ?>"/>    
    <input id="item" name="item" type="text" autocomplete="off" value="<?= $this->list->BooTitle . ' - ' . $this->list->BooAuthor; ?>"/> 
    <input id="cant" name="cant" type="text" autocomplete="off" value="1"/> 
    <input id="precio" name="precio" type="text" autocomplete="off" value="<?= $this->list->BooPrice; ?>"/> 
    <input id="fecha" name="fecha" type="text" autocomplete="off" value="<?= date('Y-m-d'); ?>"/>    
    <input id="sesion" name="sesion" type="text" autocomplete="off" value="<?= get('cliente'); ?>"/> 
    <a onclick="SaveVenta();" type="button" >Registrar</a>
</form>

<script>
    setImage = function (id) {
        var url = $("#thumb-" + id).attr("rel");
        console.log(this);
        $('#book-image').css('background-image', 'url(' + url + ')');
    }
</script>
<!--                        incluir este script en el widget-->
