<?PHP

$db = new Entities_BookMall();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado BookMall ";
$grid->setIdField("BooId");
$grid->setLanField("BooLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "BooTitle" => "Titulo","BooPrice" => "Precio", "BooStatus" => "Estado"));
$grid->setFilters(array("BooTitle" => get('BooTitle')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Books/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Books/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Books/Delete/id/_ID_' . "':'';");

$grid->customField("BooStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
