<section class="col-xs-12">

    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-12 content-header-1-title bg-bookmall">
                <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtBookMall")->TxtDescription ?></h3>
            </div>
        </div>
    </div>
    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShowBookMall_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool notas-items">
        <div class="row">
            <?php foreach ($this->list as $new) { ?>
                <div class="col-sm-6 col-md-4 notas-item">
                    <div class="square"
                         style="background-image:url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $new->BooImage; ?>);background-size:cover ">
                        <div class="square square-hover bg-white">

                            <div class="content">
                                <a href="#">
                                    <h3><?PHP echo $new->BooTitle; ?></h3>
                                </a>
                                <p>
                                    <?PHP echo $new->BooContent; ?>
                                    <a href="#" class="tag bg-tag-bookmall">
                                        <span>ver mas</span>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "books/" . $new->BooId); ?>">
                        <h3><?PHP echo $new->BooTitle; ?>
                            <small class="tag bg-tag-bookmall pull-right"> comprar</small>
                        </h3>
                    </a>
                </div>
            <?php } ?>     

        </div>
    </div>
</section>


