<section class="col-xs-12">

    <div class="container-fluid content-header-1 full-width">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-12 content-header-1-title m_amarillo">
                <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtBookMall")->TxtDescription ?></h3>
            </div>
        </div>
    </div>

    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShowBookMall_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>

    <h4 style="color:white;font-size: 22px; margin:25px 0 10px">Actualmente en stock:</h4>
    <div class="container-fluid content-tool notas-items">
        <div class="row">
            <?php foreach ($this->list as $new) { ?>
                <div class="col-sm-6 col-md-4 notas-item">
                    <div class="square"
                         style="background-image:url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $new->BooImage; ?>);background-size:cover ">
                        <div class="square square-hover bg-white">

                            <div class="content">
                                <a href="#">
                                    <h3><?PHP echo $new->BooTitle; ?></h3>
                                </a>
                                <p>
                                    <?PHP echo $new->BooContent; ?>
                                    <a href="#" class="tag bg-tag-bookmall">
                                        <span>ver mas</span>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "books/" . $new->BooId); ?>">
                        <h3><?PHP echo $new->BooTitle; ?>
                            <small class="tag m_amarillo pull-right"> comprar</small>
                        </h3>
                    </a>
                </div>
            <?php } ?>

        </div>
    </div>
</section>

<div class="row" style="margin-top: 15px; margin-bottom: 15px;">
    <div class="col-xs-12">
        <?php Advertising_Widget_Ad::getInstance()->setType('F')->setLimit(1)->renderB(); ?>
    </div>
</div>

<div class="col-sm-12" style="padding: 0 15px">
    <div class="row">
        <section class="col-sm-4 pauta-widget">
            <div class="container-fluid content-header-1">
                <?php Public_Widget_Pauta::getInstance()->setLan($this->lan)->render(); ?>

        </section>
        <section class="col-sm-4 pauta-widget">
            <div class="container-fluid content-header-1">
                <?php Public_Widget_Pauta::getInstance()->setLan($this->lan)->render(); ?>

        </section>
        <section class="col-sm-4 pauta-widget">
            <div class="container-fluid content-header-1">
                <?php Public_Widget_Pauta::getInstance()->setLan($this->lan)->render(); ?>
        </section>
    </div>
</div>



