<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-3 content-header-1-title m_verde">
                <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitlePauta')->TxtDescription; ?></h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool pauta-desc">
                <span
                    class="text-gray"><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtSubTitlePauta')->TxtDescription; ?></span>
            </div>
        </div>
    </div>

    <form id="searchForm" method="POST"
          action="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "tools/"); ?>" onsubmit="">
        <input type="hidden" name="page" id="page" value="1">
    </form>

    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShowsPauta_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool bg-white">
        <div class="row descarga-items">
            <div class="col-xs-12 descarga-item" style="text-align: center">
                <a href="#" class="content-social-link"> <i class="fa fa-twitter"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-facebook"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-instagram"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-youtube"></i></a>
            </div>
        </div>
        <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitlePautaNosotros')->TxtDescription; ?></h3>


        <div class="row descarga-items">
            <div class="col-xs-12 descarga-item text-center">
                <p>
                    <?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtContentPauta')->TxtDescription; ?>

                </p>
            </div>
        </div>

        <div class="row">
            <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitleTarifarioImpresa')->TxtDescription; ?></h3>
        </div>

        <div class="row tarifario-items">
            <?php foreach ([1, 2, 3, 4, 5, 6, 7, 8] as $var) : ?>

                <div class="col-xs-12 tarifario-item">
                    <img class="img-responsive"
                         src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/tarifario_00<?= $var ?>.jpg"
                         alt="">
                </div>

            <?php endforeach; ?>
        </div>


        <div class="row">
            <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitleTarifarioDigital')->TxtDescription; ?></h3>
        </div>

        <div class="row tarifario-web-items">
            <?php foreach ([1, 2, 3, 4, 5, 6] as $var) : ?>
                <div class="col-xs-12 tarifario-web-item">
                    <img class="img-responsive"
                         src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/tarifario-web_00<?= $var ?>.jpg"
                         alt="">
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

<script>
    $('.tarifario-items').slick({
        dots: true,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear',
        arrows: false
    });
    $(".tarifario-items .slick-dots li#slick-slide00").html("Portada interior o retira de tapa");
    $(".tarifario-items .slick-dots li#slick-slide01").html("Doble pagina");
    $(".tarifario-items .slick-dots li#slick-slide02").html("Pagina interior");
    $(".tarifario-items .slick-dots li#slick-slide03").html("Tercer pagina completa");
    $(".tarifario-items .slick-dots li#slick-slide04").html("Pagina reportaje");
    $(".tarifario-items .slick-dots li#slick-slide05").html("Media pagina vertical");
    $(".tarifario-items .slick-dots li#slick-slide06").html("interior contratapa");
    $(".tarifario-items .slick-dots li#slick-slide07").html("Contratapa");


    $('.tarifario-web-items').slick({
        dots: true,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear',
        arrows: false
    });


    $(".tarifario-web-items .slick-dots li#slick-slide10").html("290px X 600px");
    $(".tarifario-web-items .slick-dots li#slick-slide11").html("290px X 300px");
    $(".tarifario-web-items .slick-dots li#slick-slide12").html("290px X 600px");
    $(".tarifario-web-items .slick-dots li#slick-slide13").html("570px X 200px");
    $(".tarifario-web-items .slick-dots li#slick-slide14").html("1000px X 220px");
    $(".tarifario-web-items .slick-dots li#slick-slide15").html("760px X 530px");

</script>
<script>
    function changeTool(page) {
        $('#page').val(page);
        $('#searchForm').submit();
    }
</script>