<div class="col-xs-12 col-md-12">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-3 content-header-1-title m_verde">
                <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitlePauta')->TxtDescription; ?></h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool pauta-desc">
                <span
                    class="text-gray"><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtSubTitlePauta')->TxtDescription; ?></span>
            </div>
        </div>
    </div>

    <form id="searchForm" method="POST"
          action="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "tools/"); ?>" onsubmit="">
        <input type="hidden" name="page" id="page" value="1">
    </form>

    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShowsPauta_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool bg-white">
        <div class="row descarga-items">
            <div class="col-xs-12 descarga-item" style="text-align: center">
                <a href="#" class="content-social-link"> <i class="fa fa-twitter"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-facebook"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-instagram"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-youtube"></i></a>
            </div>
        </div>
        <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitlePautaNosotros')->TxtDescription; ?></h3>


        <div class="row descarga-items">
            <div class="col-xs-12 descarga-item text-center">
                <p>
                    <?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtContentPauta')->TxtDescription; ?>

                </p>
            </div>
        </div>

        <div class="row">
            <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitleTarifarioImpresa')->TxtDescription; ?></h3>
        </div>

        <div class="row tarifario-items">
            <?php foreach ([1, 2, 3, 4, 5, 6, 7, 8] as $var) : ?>

                <div class="col-xs-12 tarifario-item">
                    <a data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">
                        <img class="img-responsive" style="max-height: 540px"
                             src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/tarifario_00<?= $var ?>.jpg"
                             alt="">
                    </a>
                </div>

            <?php endforeach; ?>
        </div>


    </div>
</div>

<style>
    .modal-backdrop {
        z-index: -2000;
    }

    .modal-dialog {

        margin: 50px auto;
    }
</style>
<div class="modal" id="exampleModal" tabindex="-99999999999" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Generar Orden de compra</h4>
            </div>
            <div class="modal-body">
                <form id="formContact">
                    <div class="form-group">
                        <label for="recipient-name"
                               class="control-label"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactNombre")->TxtDescription ?></label>
                        <input type="text" class="form-control" id="name">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name"
                               class="control-label"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactTelefono")->TxtDescription ?></label>
                        <input type="text" class="form-control" id="phone">
                    </div>
                    <div class="form-group">
                        <label for="recipient-name"
                               class="control-label"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactEmail")->TxtDescription ?></label>
                        <input type="text" class="form-control" id="email">
                    </div>
                    <div class="form-group">
                        <label for="message-text"
                               class="control-label"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactMensaje")->TxtDescription ?></label>
                        <textarea class="form-control" id="message"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactCancelar")->TxtDescription ?></button>
                <button onclick="//sendContact();" type="button"
                        class="btn btn-primary"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactEnviar")->TxtDescription ?></button>
            </div>
        </div>
    </div>
</div>

<script>
    $('.tarifario-items').slick({
        dots: true,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear',
        arrows: false
    });
    $(".tarifario-items .slick-dots li#slick-slide00").html("Portada interior o retira de tapa");
    $(".tarifario-items .slick-dots li#slick-slide01").html("Doble pagina");
    $(".tarifario-items .slick-dots li#slick-slide02").html("Pagina interior");
    $(".tarifario-items .slick-dots li#slick-slide03").html("Tercer pagina completa");
    $(".tarifario-items .slick-dots li#slick-slide04").html("Pagina reportaje");
    $(".tarifario-items .slick-dots li#slick-slide05").html("Media pagina vertical");
    $(".tarifario-items .slick-dots li#slick-slide06").html("interior contratapa");
    $(".tarifario-items .slick-dots li#slick-slide07").html("Contratapa");


    $('.tarifario-web-items').slick({
        dots: true,
        infinite: true,
        speed: 500,
        fade: true,
        cssEase: 'linear',
        arrows: false
    });


    $(".tarifario-web-items .slick-dots li#slick-slide10").html("290px X 600px");
    $(".tarifario-web-items .slick-dots li#slick-slide11").html("290px X 300px");
    $(".tarifario-web-items .slick-dots li#slick-slide12").html("570px X 200px");
    $(".tarifario-web-items .slick-dots li#slick-slide13").html("1000px X 220px");
    $(".tarifario-web-items .slick-dots li#slick-slide14").html("760px X 530px");

</script>
<script>
    function changeTool(page) {
        $('#page').val(page);
        $('#searchForm').submit();
    }


    var timer = $.timer(function () {
        timer.stop();
        swal({
                title: "Dejanos tu correo electronico",
                text: "Te enviaremos mas información",
                type: "input",
                confirmButtonColor: "#80B519",
                showCancelButton: true,
                closeOnConfirm: false,
                animation: "slide-from-top",
                inputPlaceholder: "Correo electronico"
            },
            function (inputValue) {
                if (inputValue === false) {
                    return false;
                    timer.stop();
                }


                if (inputValue === "") {
                    swal.showInputError("Ingresa tu correo electronico.");
                    timer.stop();
                    return false
                }

                swal("Excelente!", "You wrote: " + inputValue, "success");
                timer.stop();
            });
    });
    timer.set({time: 10000, autostart: true});

</script>