<div class="col-xs-12 col-md-8">

    <div class="container-fluid content-header-1">
        <div class="row">
            <div class="col-sm-3 content-header-1-title m_verde">
                <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitlePauta')->TxtDescription; ?></h3>
            </div>
            <div class="col-sm-9 content-header-1-options bg-blue-dark-tool pauta-desc">
                <span class="text-gray"><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtSubTitlePauta')->TxtDescription; ?></span>
            </div>
        </div>
    </div>

    <form id="searchForm" method="POST"
          action="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, "tools/"); ?>" onsubmit="">
        <input type="hidden" name="page" id="page" value="1">
    </form>

    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShowsPauta_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool bg-white">
        <div class="row descarga-items">
            <div class="col-xs-12 descarga-item" style="text-align: center">
                <a href="#" class="content-social-link"> <i class="fa fa-twitter"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-facebook"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-instagram"></i></a>
                <a href="#" class="content-social-link"> <i class="fa fa-youtube"></i></a>
            </div>
        </div>
        <h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitlePautaNosotros')->TxtDescription; ?></h3>



        <div class="row descarga-items">
            <div class="col-xs-12 descarga-item text-center">
                <p>
                    <?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtContentPauta')->TxtDescription; ?>
                    
                </p>
            </div>
        </div>

        <div class="row"><h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitleTarifarioImpresa')->TxtDescription; ?></h3></div>

        <?php foreach ([1, 2, 3] as $var) : ?>
            <div class="row descarga-items">
                <div class="col-xs-12 descarga-item">
                    <img class="img-responsive"
                         src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/pauta-<?= $var ?>.jpg" alt="">
                    <div class="row descarga-item-detail">
                        <div class="col-lg-3 col-sm-6 col-xs-12">
                            <div class="form-group has-success">
                                <label class="control-label" for="inputSuccess1">Visibilidad</label>
                                <input type="text" class="form-control" id="visibilidad"
                                       aria-describedby="helpBlock2">
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-6 col-xs-12">
                            <div class="form-group has-success">
                                <label class="control-label" for="inputSuccess1">Descripcion</label>
                                <input type="text" class="form-control" id="descripcion"
                                       aria-describedby="helpBlock2">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-xs-12">
                            <div class="form-group has-success">
                                <label class="control-label" for="inputSuccess1">&nbsp</label>
                                <a href="#" class="form-control btn btn-block tag bg-note-purple  btn-pauta">Generar
                                    orden de
                                    compra</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <div class="row"><h3><?php echo Texts_Helper_Text::getInstance()->get($this->lan, 'txtTitleTarifarioDigital')->TxtDescription; ?></h3></div>

        <?php foreach ([1, 2, 3] as $var) : ?>
            <div class="row descarga-items">
                <div class="col-xs-12 descarga-item">
                    <div class="row">
                        <div class="col-md-9">
                            <img class="img-responsive"
                                 src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/pauta-<?= $var ?>.jpg"
                                 alt="">
                        </div>
                        <div class="col-md-3">
                            <img class="img-responsive"
                                 src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/pauta-<?= $var ?>.jpg"
                                 alt="">
                        </div>
                    </div>
                    <div class="row descarga-item-detail">
                        <div class="col-lg-3 col-sm-6 col-xs-12">
                            <div class="form-group has-success">
                                <label class="control-label" for="inputSuccess1">Visibilidad</label>
                                <input type="text" class="form-control" id="visibilidad"
                                       aria-describedby="helpBlock2">
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-6 col-xs-12">
                            <div class="form-group has-success">
                                <label class="control-label" for="inputSuccess1">Descripcion</label>
                                <input type="text" class="form-control" id="descripcion"
                                       aria-describedby="helpBlock2">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-xs-12">
                            <div class="form-group has-success">
                                <label class="control-label" for="inputSuccess1">&nbsp</label>
                                <a href="#" class="form-control btn btn-block tag bg-note-purple  btn-pauta">Generar
                                    orden de
                                    compra</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script>

    function changeTool(page) {
        $('#page').val(page);
        $('#searchForm').submit();
    }

</script>