<?PHP

$db = new Entities_Calendar();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Calendar";
$grid->setIdField("CalId");
$grid->setLanField("CalLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "CalEvent" => "Evento", "CalDate" => "Fecha", "CalStatus" => "Estado"));
$grid->setFilters(array("CalEvent" => get('CalEvent')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Calendar/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Calendar/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Calendar/Delete/id/_ID_' . "':'';");

$grid->customField("CalStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
