<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
        <title>MARKETING NEWS</title>
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel='stylesheet' id='open-sans-css'
              href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1'
              type='text/css' media='all'/>
        <link
            href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,700,800%7CPlayfair+Display:400,400italic,700,900&amp;subset=greek,latin,latin"
            rel="stylesheet" type="text/css">


        <!-- Fav and Touch Icons -->       

        <link rel="apple-touch-icon" sizes="180x180" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
        <link rel="mask-icon" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
              type="image/x-icon"/>


        <?PHP
        Com_Helper_Style::getInstance()
                ->addFile("Public/bootstrap.css")
                ->addFile("Public/font-awesome.css")
                ->addFile("Public/slick.css")
                ->addFile("Public/slick-theme.css")
                ->addFile("Public/swiper.css")
                ->addFile("Public/animate.css")
                ->addFile("Public/owl.carousel.css")
                ->addFile("Public/materialicon.css")
                ->addFile("Public/marketing-intro.css")
                ->addFile("Public/jquery.fancybox.css")
                ->addFile("Public/jBox.css")
                ->addFile("Public/sweetalert.css");

        echo Com_Helper_Style::getInstance();
        ?>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <?php
        Com_Helper_Script::getInstance()
                ->addFile("Public/jquery.js")
                ->addFile("Public/bootstrap.js")
                ->addFile("Public/slick.min.js")
                ->addFile("Public/pathformer.js")
                ->addFile("Public/vivus.js")
                ->addFile("Public/owl.carousel.js")
                ->addFile("Public/marketing.js")
                ->addFile("Public/rdcalendar.js")
                ->addFile("Public/swiper.jquery.js")
                ->addFile("Public/login.js")
                ->addFile("Public/jquery.jbox.min.js")
                ->addFile("Public/sweetalert.min.js")
                ->addFile("Public/jquery.fancybox.js")
        ;
        echo Com_Helper_Script::getInstance();

        $client = get('sessionCliente');
        ?>
        <?php Public_Widget_Loading::getInstance()->render(); ?>
    </head>

    <body class="desktop">
        <section id="preload">
            <div id="preloader">
                <div class="preloader-item preloader-item1"></div>
                <div class="preloader-item preloader-item2"></div>
                <div class="preloader-item preloader-item3"></div>
            </div>
        </section>

        <section class="main-menu">
            <div class="container-fluid">
                <div class="row">
                    <div class="menu-content col-md-6">
                        <div class="menu-container alt" style="display: none">

                            <a class="logo" href="<?= Com_Helper_Url::getInstance()->urlBase . '/' . $this->lan->LanCode . '/page/home.html'; ?>">
                                <img alt="logo"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
                            </a>
                            <a href="javascript:void(0)" onclick="toogleMenu();">
                                <i class="fa fa-close" aria-hidden="true"></i>
                            </a>

                        </div>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="menu-nav">
                                        <ul>
                                            <?PHP Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="rowgit ">
                                <div class="col-md-12">
                                    <div class="menu-redes">
                                        <ul class="list-inline">
                                            <li>siguenos en</li>
                                            <li><a target="_blank"
                                                   href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkFacebook')->LinUrl; ?>"
                                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-facebook"></a>
                                            </li>
                                            <li><a target="_blank"
                                                   href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkTwitter')->LinUrl; ?>"
                                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-twitter"></a>
                                            </li>
                                            <li><a target="_blank"
                                                   href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkInstagram')->LinUrl; ?>"
                                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-instagram"></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="row hidden">
                                <div class="col-md-offset-2 col-md-10">
                                    <div class=" menu-nav">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="menu-container" style="display: none">
            <a class="logo" href="<?= Com_Helper_Url::getInstance()->urlBase . '/' . $this->lan->LanCode . '/page/home.html'; ?>">
                <img alt="logo"
                     src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
            </a>
            <ul>
                <?php if ($client != '0'): ?>
                    <li><a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/es/profile" title="Editar Perfil"
                           alt="Editar Perfil <?= $client->CliName; ?>"> <i class="fa fa-user"></i> <?= $client->CliName; ?> </a></li>
                    <li><a onclick="closeSession();" alt="Logout"><i class="fa mkt-logout"></i></a></li>
                <?php else : ?>
                    <li><a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/es/login" title="Login" alt="Login"><i class="fa mkt-login"></i></a>
                    </li>
                <?php endif; ?>
                <li><a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars" aria-hidden="true"></i></a></li>
            </ul>
        </div>

        <section class="section-sm-60">
            <div class="container container-mod-1">
                <div class="row row-no-gutter">
                    <section class="col-xs-12">

                        <div class="container-fluid content-header-1 full-width">
                            <div class="row">
                                <div class="col-sm-12 content-header-1-title bg-suscription">
                                    <h3><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtSuscripcion")->TxtDescription ?></h3>
                                </div>
                            </div>
                        </div>


                    </section>
                    <section class="col-xs-12"> 
                        <div class="col-md-6" style="padding-top:20px; height: 400px; background: #7d16ee;">
                            <form id="formContact" class="formContacto">
                                <div class="form-group">                                    
                                    <input type="text" class="form-control" id="name" placeholder="<?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactNombre")->TxtDescription ?>">
                                </div>                            
                                <div class="form-group">                                    
                                    <input type="text" class="form-control" id="phone" placeholder="<?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactTelefono")->TxtDescription ?>">
                                </div>
                                <div class="form-group">                                    
                                    <input type="text" class="form-control" id="email" placeholder="<?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactEmail")->TxtDescription ?>">
                                </div>
                                <div class="form-group">                                    
                                    <textarea class=" mensaje" id="message" placeholder="<?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactMensaje")->TxtDescription ?>"></textarea>
                                </div>
                                <div class="form-group"> 
                                    <button onclick="sendContact();" type="button" class="boton"><?= Texts_Helper_Text::getInstance()->get($this->lan, "txtContactEnviar")->TxtDescription ?></button>
                                </div>
                            </form>



                        </div>
                        <div class="col-md-6" style="padding: 0;">
                            <div id="map" style="height: 400px;"></div>
                        </div>
                    </section>



                </div>

            </div>
        </div>
    </section>

    <?php Public_Widget_Footer::getInstance()->setLan($this->lan)->render(); ?>

    <script type="text/javascript">

        var map;
        function initMap() {
            map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: -17.7534325, lng:-63.170877},
                zoom: 17
            });

            var contentString = '<strong>Llámanos:</strong>'+
                    '<br> 71011835 67702060'+
                    '<br><br>'+
                    '<strong>Encuéntranos:</strong>'+
                    '<br>Av. Beni entre 3er y 4to anillo Calle 7 Este, Nro. 5 Barrio Hamacas'+
                    '<br><br>'+
                    '<strong>Escríbenos:</strong>'+
                    '<br>leslie@exma.com.bo <br> gabriela@exma.com.bo'+
                    '<br><br>'
                    
                    ;

            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });

            var marker = new google.maps.Marker({
                position: {lat: -17.753172, lng: -63.170480},
                map: map,
                title: 'Uluru (Ayers Rock)'
            });
            
                infowindow.open(map, marker);
            
        }

    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBMGB3_vf_4X3cpQa11DXKV3K2p0i0Mo3s&callback=initMap"
    async defer></script>
</body>
</html>