<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
    <title>MARKETING NEWS</title>
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel='stylesheet' id='open-sans-css'
          href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1'
          type='text/css' media='all'/>
    <link
        href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,700,800%7CPlayfair+Display:400,400italic,700,900&amp;subset=greek,latin,latin"
        rel="stylesheet" type="text/css">

    <!-- Fav and Touch Icons -->

    <link rel="apple-touch-icon" sizes="180x180"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png"
          sizes="32x32">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png"
          sizes="16x16">
    <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
    <link rel="mask-icon"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/safari-pinned-tab.svg"
          color="#5bbad5">
    <link rel="shortcut icon"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
          type="image/x-icon"/>


    <?PHP
    Com_Helper_Style::getInstance()
        ->addFile("Public/bootstrap.css")
        ->addFile("Public/font-awesome.css")
        ->addFile("Public/slick.css")
        ->addFile("Public/slick-theme.css")
        ->addFile("Public/swiper.css")
        ->addFile("Public/animate.css")
        ->addFile("Public/owl.carousel.css")
        ->addFile("Public/materialicon.css")
        ->addFile("Public/marketing-intro.css")
        ->addFile("Public/jquery.fancybox.css")
        ->addFile("Public/ModalBorder.css")
        ->addFile("Public/jBox.css")
        ->addFile("Public/sweetalert.css");

    echo Com_Helper_Style::getInstance();
    ?>
    <!--    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>-->
    <!--    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>-->
    <?php
    Com_Helper_Script::getInstance()
        ->addFile("Public/jquery.js")
        ->addFile("Public/bootstrap.js")
        ->addFile("Public/slick.min.js")
        ->addFile("Public/pathformer.js")
        ->addFile("Public/vivus.js")
        ->addFile("Public/owl.carousel.js")
        ->addFile("Public/marketing.js")
        ->addFile("Public/rdcalendar.js")
        ->addFile("Public/swiper.jquery.js")
        ->addFile("Public/login.js")
        ->addFile("Public/jquery.fancybox.js")
        ->addFile("Public/jquery.jbox.min.js")
        ->addFile("Public/sweetalert.min.js");

    echo Com_Helper_Script::getInstance();


    $client = get('sessionCliente');
    ?>
    <?php Public_Widget_Loading::getInstance()->render(); ?>
</head>

<body class="desktop">
<section id="preload">
    <div id="preloader">
        <div class="preloader-item preloader-item1"></div>
        <div class="preloader-item preloader-item2"></div>
        <div class="preloader-item preloader-item3"></div>
    </div>
</section>

<section class="main-menu">
    <div class="container-fluid">
        <div class="row">
            <div class="menu-content col-md-6">
                <div class="menu-container alt" style="display: none">


                    <a class="logo" href="<?= Com_Helper_Url::getInstance()->urlBase; ?>">
                        <img alt="logo"
                             src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
                    </a>


                    <a href="javascript:void(0)" onclick="toogleMenu();">
                        <i class="fa fa-close" aria-hidden="true"></i>
                    </a>

                </div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="menu-nav">
                                <ul>
                                    <?PHP Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="rowgit ">
                        <div class="col-md-12">
                            <div class="menu-redes">
                                <ul class="list-inline">
                                    <li>siguenos en</li>
                                    <li><a target="_blank"
                                           href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkFacebook')->LinUrl; ?>"
                                           class="icon icon-sm icon-white icon-circle icon-border fa fa-facebook"></a>
                                    </li>
                                    <li><a target="_blank"
                                           href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkTwitter')->LinUrl; ?>"
                                           class="icon icon-sm icon-white icon-circle icon-border fa fa-twitter"></a>
                                    </li>
                                    <li><a target="_blank"
                                           href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkInstagram')->LinUrl; ?>"
                                           class="icon icon-sm icon-white icon-circle icon-border fa fa-instagram"></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row hidden">
                        <div class="col-md-offset-2 col-md-10">
                            <div class=" menu-nav">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="menu-container" style="display: none">
    <a class="logo" href="<?= Com_Helper_Url::getInstance()->urlBase; ?>">
        <img alt="logo"
             src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
    </a>

    <ul>
        <?php if ($client != '0'): ?>
            <li><a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/es/profile" title="Editar Perfil"
                   alt="Editar Perfil <?= $client->CliName; ?>"> <i class="fa fa-user"></i> <?= $client->CliName; ?>
                </a></li>
            <li><a onclick="closeSession();" alt="Logout"><i class="fa mkt-logout"></i></a></li>
        <?php else : ?>
            <li><a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/es/login" title="Login" alt="Login"><i
                        class="fa mkt-login"></i></a>
            </li>
        <?php endif; ?>
        <li><a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars" aria-hidden="true"></i></a></li>
    </ul>
</div>

<section>
    <!-- Swiper-->
    <!-- Slider main container -->
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <?php SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
    </div>
</section>
<!-- print resent section-->
<?php Notes_Widget_Recientes::getInstance()->setLan($this->lan)->setLimit(12)->render(); ?>

<section class="section-sm-60">
    <div class="container container-mod-1" style="margin-bottom: 15px">
        <?php Advertising_Widget_Ad::getInstance()->setType('I')->setLimit(1)->renderI(); ?>

    </div>
    <div class="container container-mod-1">
        <div class="row row-no-gutter">
            <div class="col-xs-12 col-md-8">
                <!--Section 1-->
                <div class="row row-no-gutter text-left row-mod-1">
                    <div class="col-xs-12 col-md-8">
                        <div class="post-news height-520 bg-item-5 post-news-mod-1 bg-primary"
                             style="background: linear-gradient(rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatId) ?>,0.6),rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatId) ?>,0.6)), url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatImage; ?>); background-size: cover">
                            <div class="post-body">
                                <h4>
                                    <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatLinkModule); ?>"><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatAlias; ?></a>
                                </h4>

                                <p><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatDescription; ?></p>
                            </div>
                            <div class="post-footer">
                                <span class="post-count"> </span>
                                <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_IMPORTANT'))->CatLinkModule); ?>"
                                   class="btn btn-transparent">
                                    <i class="fa fa-arrow-right"
                                       style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;padding-top: 5px;"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-md-4">
                        <div class="row row-no-gutter">
                            <div class="col-xs-12 col-sm-6 col-md-12">
                                <div class="post-news height-260 post-news-mod-1 "
                                     style="background: rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_1'))->CatId) ?>,1)">
                                    <div class="post-body">
                                        <h4>
                                            <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_1'))->CatLinkModule); ?>"><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_1'))->CatAlias; ?></a>
                                        </h4>
                                        <p><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_1'))->CatDescription; ?></p>
                                    </div>
                                    <div class="post-footer">
                                        <span class="post-count"> </span>
                                        <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_1'))->CatLinkModule); ?>"
                                           class="btn btn-transparent">
                                            <i class="fa fa-arrow-right"
                                               style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;padding-top: 5px;"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-md-12">
                                <div class="post-news height-260 post-news-mod-1"
                                     style="background: rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_2'))->CatId) ?>,1)">
                                    <div class="post-body">
                                        <h4>
                                            <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_2'))->CatLinkModule); ?>"><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_2'))->CatAlias; ?></a>
                                        </h4>

                                        <p><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_2'))->CatDescription; ?></p>
                                    </div>
                                    <div class="post-footer"><span class="post-count"> </span>
                                        <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_2'))->CatLinkModule); ?>"
                                           class="btn btn-transparent">
                                            <i class="fa fa-arrow-right"
                                               style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;padding-top: 5px;"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row row-no-gutter text-left row-mod-1">
                    <div class="col-xs-12 col-md-4">
                        <div class="post-news height-260 post-news-mod-1"
                             style="background: rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_3'))->CatId) ?>,1)">
                            <div class="post-body">
                                <h4>
                                    <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_3'))->CatLinkModule); ?>"><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_3'))->CatAlias; ?></a>
                                </h4>

                                <p><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_3'))->CatDescription; ?></p>
                            </div>
                            <div class="post-footer"><span class="post-count"> </span>
                                <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_3'))->CatLinkModule); ?>"
                                   class="btn btn-transparent">
                                    <i class="fa fa-arrow-right"
                                       style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;padding-top: 5px;"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="post-news height-260 post-news-mod-1"
                             style="background: rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_4'))->CatId) ?>,1)">
                            <div class="post-body">
                                <h4>
                                    <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_4'))->CatLinkModule); ?>"><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_4'))->CatAlias; ?></a>
                                </h4>

                                <p><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_4'))->CatDescription; ?></p>
                            </div>
                            <div class="post-footer"><span class="post-count"> </span>
                                <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_4'))->CatLinkModule); ?>"
                                   class="btn btn-transparent">
                                    <i class="fa fa-arrow-right"
                                       style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;padding-top: 5px;"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="post-news height-260 bg-item-6 post-news-mod-1"
                             style="background: linear-gradient(rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatId) ?>,0.6),rgba(<?= Categories_Helper_Category::getInstance()->getHexa($this->lan, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatId) ?>,0.6)), url(<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatImage; ?>); background-size: cover">
                            <div class="post-body">
                                <h4>
                                    <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatLinkModule); ?>"><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatAlias; ?></a>
                                </h4>

                                <p><?= Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatDescription; ?></p>
                            </div>
                            <div class="post-footer hi"><span class="post-count"> </span>
                                <a href="<?PHP echo Com_Helper_Url::getInstance()->generateUrl($this->lan->LanCode, Categories_Helper_Category::getInstance()->get($this->lan, Configurations_Helper_Configuration::getInstance()->getKey('CAT_5'))->CatLinkModule); ?>"
                                   class="btn btn-transparent">
                                    <i class="fa fa-arrow-right"
                                       style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;padding-top: 5px;"></i></a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="row row row-no-gutter text-center text-sm-left">
                    <div class="col-xs-12">
                        <?php Advertising_Widget_Ad::getInstance()->setType('F')->setLimit(1)->renderF(); ?>
                    </div>
                </div>


                <div class="row row row-no-gutter text-center text-sm-left">

                    <?php Notes_Widget_MostViewed::getInstance()->setLan($this->lan)->setLimit(2)->render(); ?>
                </div>
                <div class="row row row-no-gutter text-center text-sm-left">
                    <div class="col-xs-12">
                        <?php Notes_Widget_Important::getInstance()->setLan($this->lan)->setLimit(1)->render(); ?>
                    </div>
                </div>
                <div class="row row row-no-gutter text-center text-sm-left">
                    <div class="col-xs-12">
                        <?php Advertising_Widget_Ad::getInstance()->setType('B')->setLimit(1)->renderB(); ?>
                    </div>
                </div>


                <!--                        <nav class="text-left">
                                            <ul class="pagination">
                                                <li class="active"><a href="#">1</a></li>
                                                <li><a href="#">2</a></li>
                                                <li><a href="#">3</a></li>
                                                <li><a href="#">4</a></li>
                                                <li><a href="#">5</a></li>
                                                <li>
                                                    <a href="#" class="nav-next">
                                                        <i class="fa fa-arrow-right"
                                                           style="font-size: 24px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;"></i>
                                                    </a>
                                                </li>
                                            </ul>
                                        </nav>-->
            </div>
            <div class="side-right col-xs-12 col-md-4">
                <!--Sidebar-->
                <div class="sidebar offset-top-40 offset-md-top-0">
                    <!--SECCION BUSQUEDA -->
                    <?php Public_Widget_Busqueda::getInstance()->setLan($this->lan)->setType("notas")->render(); ?>
                    <!--SECCION PUBLICIDAD -->
                    <?php Advertising_Widget_Ad::getInstance()->setType('C')->setLimit(1)->renderC(); ?>
                    <!--SECCION SOCIAL MEDIA -->
                    <?php Public_Widget_SocialMedia::getInstance()->setLan($this->lan)->render(); ?>
                    <!--SECCION NEWSLETTER -->
                    <?php Public_Widget_Newsletter::getInstance()->setLan($this->lan)->render(); ?>

                    <div class="sidebar-module">
                        <!--SECCION PUBLICIDAD -->
                        <?php Advertising_Widget_Ad::getInstance()->setType('E')->setLimit(1)->renderE(); ?>
                    </div>

                    <div class="sidebar-module module-social bg-primary text-left">
                        <h5>Otro cool widget</h5>

                    </div>

                    <!--SECCION CALENDARIO -->
                    <?php Public_Widget_Calendario::getInstance()->setLan($this->lan)->render(); ?>
                    <!--SECCION SUSCRIBITE -->
                    <?php Public_Widget_Suscribite::getInstance()->setLan($this->lan)->render(); ?>
                    <!--SECCION PAUTA -->
                    <?php Public_Widget_Pauta::getInstance()->setLan($this->lan)->render(); ?>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="insta-wrap">
    <?php Public_Widget_FollowInstagram::getInstance()->setLan($this->lan)->render(); ?>
</section>
<?php Public_Widget_Footer::getInstance()->setLan($this->lan)->render(); ?>
<script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        direction: 'vertical',
        slidesPerView: 1,
        paginationClickable: true,
        spaceBetween: 30,
        autoplay: 8000,
        mousewheelControl: false,
        onTransitionStart: function (swiper) {
            toggleSwiperInnerVideos(swiper);
        },
        onTransitionEnd: function (swiper) {
            toggleSwiperCaptionAnimation(swiper);
        },
        onInit: function (swiper) {
            toggleSwiperInnerVideos(swiper);
            toggleSwiperCaptionAnimation(swiper);
            //            var swiperParalax = s.find(".swiper-parallax");

            //            for (var k = 0; k < swiperParalax.length; k++) {
            //                var $this = $(swiperParalax[k]),
            //                        speed;
            //
            //                if (parallax && !isIEBrows && !isMobile) {
            //                    if (speed = $this.attr("data-speed")) {
            //                        makeParallax($this, speed, s, false);
            //                    }
            //                }
            //            }
            $(window).on('resize', function () {
                swiper.update(true);
            })
        }
    });
    function toggleSwiperInnerVideos(swiper) {
        var prevSlide = $(swiper.slides[swiper.previousIndex]),
            nextSlide = $(swiper.slides[swiper.activeIndex]),
            videos;

        prevSlide.find("video").each(function () {
            this.pause();
        });

        videos = nextSlide.find("video");
        if (videos.length) {
            videos.get(0).play();
        }
    }

    function toggleSwiperCaptionAnimation(swiper) {
        var prevSlide = $(swiper.container),
            nextSlide = $(swiper.slides[swiper.activeIndex]);

        prevSlide
            .find("[data-caption-animate]")
            .each(function () {
                var $this = $(this);
                $this
                    .removeClass("animated")
                    .removeClass($this.attr("data-caption-animate"))
                    .addClass("not-animated");
            });

        nextSlide
            .find("[data-caption-animate]")
            .each(function () {
                var $this = $(this),
                    delay = $this.attr("data-caption-delay");

                setTimeout(function () {
                    $this
                        .removeClass("not-animated")
                        .addClass($this.attr("data-caption-animate"))
                        .addClass("animated");
                }, delay ? parseInt(delay) : 0);
            });
    }

    var owls = $('.owl-carousel');
    if (owls.length) {
        for (i = 0; i < owls.length; i++) {

            var c = $(owls[i]),
                responsive = {};

            var aliaces = ["-", "-xs-", "-sm-", "-md-", "-lg-"],
                values = [0, 480, 768, 992, 1200],
                j, k;

            for (j = 0; j < values.length; j++) {
                responsive[values[j]] = {};
                for (k = j; k >= -1; k--) {
                    if (!responsive[values[j]]["items"] && c.attr("data" + aliaces[k] + "items")) {
                        responsive[values[j]]["items"] = k < 0 ? 1 : parseInt(c.attr("data" + aliaces[k] + "items"));
                    }
                    if (!responsive[values[j]]["stagePadding"] && responsive[values[j]]["stagePadding"] !== 0 && c.attr("data" + aliaces[k] + "stage-padding")) {
                        responsive[values[j]]["stagePadding"] = k < 0 ? 0 : parseInt(c.attr("data" + aliaces[k] + "stage-padding"));
                    }
                    if (!responsive[values[j]]["margin"] && responsive[values[j]]["margin"] !== 0 && c.attr("data" + aliaces[k] + "margin")) {
                        responsive[values[j]]["margin"] = k < 0 ? 30 : parseInt(c.attr("data" + aliaces[k] + "margin"));
                    }
                }
            }

            c.owlCarousel({
                autoplay: c.attr("data-autoplay") === "true",
                loop: c.attr("data-loop") !== "false",
                items: 1,
                dotsContainer: c.attr("data-pagination-class") || false,
                navContainer: c.attr("data-navigation-class") || false,
                mouseDrag: c.attr("data-mouse-drag") !== "false",
                //                nav: c.attr("data-nav") === "true",
                nav: "true",
                //                dots: c.attr("data-dots") === "true",
                //                dotsEach: c.attr("data-dots-each") ? parseInt(c.attr("data-dots-each")) : false,
                responsive: responsive,
                navText: [],
                onInitialized: function () {
                    //                    console.log("items");
                    //                    console.log(this);
                    //                    if ($.fn.magnificPopup) {
                    //                        var o = this.$element.attr('data-lightbox') !== undefined && this.$element.attr("data-lightbox") !== "gallery",
                    //                            g = this.$element.attr('data-lightbox') === "gallery";
                    //
                    //                        console.log("log o");
                    //                        console.log(o);
                    //                        if (o) {
                    //                            for (var m = 0; m < (this.$element).length; m++) {
                    //                                var $this = $(this.$element[m]);
                    //                                $this.magnificPopup({
                    //                                    type: $this.attr("data-lightbox"),
                    //                                    callbacks: {
                    //                                        open: function () {
                    //                                            if (isTouch) {
                    //                                                $document.on("touchmove", preventScroll);
                    //                                                $document.swipe({
                    //                                                    swipeDown: function () {
                    //                                                        $.magnificPopup.close();
                    //                                                    }
                    //                                                });
                    //                                            }
                    //                                        },
                    //                                        close: function () {
                    //                                            if (isTouch) {
                    //                                                $document.off("touchmove", preventScroll);
                    //                                                $document.swipe("destroy");
                    //                                            }
                    //                                        }
                    //                                    }
                    //                                });
                    //                            }
                    //                        }
                    //
                    //                        console.log("log g");
                    //                        console.log(g);
                    //                        if (g) {
                    //                            for (var k = 0; k < (this.$element).length; k++) {
                    //                                var $gallery = $(this.$element[k]).find('[data-lightbox]');
                    //                                for (var j = 0; j < $gallery.length; j++) {
                    //                                    var $item = $gallery[j];
                    //                                    $item.addClass("mfp-" + $item.attr("data-lightbox"));
                    //                                }
                    //                                $gallery.end()
                    //                                    .magnificPopup({
                    //                                        delegate: '.owl-item [data-lightbox]',
                    //                                        type: "image",
                    //                                        gallery: {
                    //                                            enabled: true
                    //                                        },
                    //                                        callbacks: {
                    //                                            open: function () {
                    //                                                if (isTouch) {
                    //                                                    $document.on("touchmove", preventScroll);
                    //                                                    $document.swipe({
                    //                                                        swipeDown: function () {
                    //                                                            $.magnificPopup.close();
                    //                                                        }
                    //                                                    });
                    //                                                }
                    //                                            },
                    //                                            close: function () {
                    //                                                if (isTouch) {
                    //                                                    $document.off("touchmove", preventScroll);
                    //                                                    $document.swipe("destroy");
                    //                                                }
                    //                                            }
                    //                                        }
                    //                                    });
                    //                            }
                    //                        }
                    //                    }
                    //                    if (c.attr("data-active")) {
                    //                        c.trigger("to.owl.carousel", c.attr("data-active") - 1);
                    //                    }
                }
            });
        }
    }

    $('.rd-calendar').rdCalendar({
        days: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
        months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
    });

    $('.pauta-container').slick({
        dots: false,
        infinite: true,
        arrows: true,
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: false,
        autoplaySpeed: 3000
    });


</script>
</body>


</html>