<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
    <title>MARKETING NEWS</title>
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel='stylesheet' id='open-sans-css'
          href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1'
          type='text/css' media='all'/>
    <link
        href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,700,800%7CPlayfair+Display:400,400italic,700,900&amp;subset=greek,latin,latin"
        rel="stylesheet" type="text/css">


    <!-- Fav and Touch Icons -->
    <meta name="msapplication-TileColor" content="#d9534f">
    <meta name="msapplication-TileImage"
          content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/ms-icon-144x144.png">
    <meta name="msapplication-config"
          content="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public//favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <link rel="apple-touch-icon" sizes="57x57"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-icon-180x180.png">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png"
          sizes="32x32">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/android-192x192.png"
          sizes="192x192">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-96x96.png"
          sizes="96x96">
    <link rel="icon" type="image/png"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png"
          sizes="16x16">
    <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
    <link rel="shortcut icon"
          href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
          type="image/x-icon"/>
    <style>
        body {
            padding: 0;
            margin: 0
        }

        #preload {
            position: absolute;
            width: 100%;
            height: 100vh;
            z-index: 9000;
            background: white;
        }

        #preloader {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }

        .preloader-item {
            width: 80px;
            height: 80px;
            margin: 10px;
            background: #CCCCCC;
            border-radius: 10px;
            float: left;
            display: block;
        }

        .preloader-item1 {
            animation-name: pulse;
            animation-duration: 1.5s;
            animation-delay: 0.3s;
            animation-iteration-count: infinite;
        }

        .preloader-item2 {
            animation-name: pulse;
            animation-duration: 1.5s;
            animation-delay: 0.6s;
            animation-iteration-count: infinite;
        }

        .preloader-item3 {
            animation-name: pulse;
            animation-duration: 1.5s;
            animation-delay: 0.9s;
            animation-iteration-count: infinite;
        }

        @keyframes pulse {
            0% {
                background-color: #941b80;
            }
            33% {
                background-color: #e5007e;
            }
            66% {
                background-color: #e20613;
            }
            100% {
                background-color: #941b80;
            }
        }
    </style>

    <?PHP
    Com_Helper_Style::getInstance()
        ->addFile("Public/bootstrap.css")
        ->addFile("Public/font-awesome.css")
        ->addFile("Public/slick.css")
        ->addFile("Public/slick-theme.css")
        ->addFile("Public/marketing-intro.css")
        ->addFile("Public/marketing-header.css")
       ;
    echo Com_Helper_Style::getInstance();

    Com_Helper_Script::getInstance()
        ->addFile("Public/bootstrap.js")
        ->addFile("Public/slick.min.js")
        ->addFile("Public/pathformer.js")
        ->addFile("Public/vivus.js")
        ->addFile("Public/marketing.js")
        ->addFile("Public/contact.js")
        ->addFile("Public/map.js");
    ?>
</head>

<body class="index-page">
<section id="preload">
    <div id="preloader">
        <div class="preloader-item preloader-item1"></div>
        <div class="preloader-item preloader-item2"></div>
        <div class="preloader-item preloader-item3"></div>
    </div>
</section>

<section class="main-menu">
    <div class="container-fluid">
        <div class="row">
            <div class="menu-content col-md-6">
                <div class="menu-container" style="display: none">
                    <img class="logo" alt="logo" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
                    <a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars" aria-hidden="true"></i></a>
                </div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="menu-cerrar">
                                <a href="javascript:void(0)" onclick="toogleMenu();"> <i class="fa fa-close"></i></a>
                            </div>
                        </div>
                        <div class="col-md-10">
                            <div class=" menu-nav">
                                <ul>
                                    <li><a href="#" class="menu-padre active">mkt</a>
                                        <ul class="menu-items active">
                                            <li class="active"><a href="#" class="menu-item">Brand</a></li>
                                            <li><a href="#" class="menu-item">Publicidad</a></li>
                                            <li><a href="#" class="menu-item">Social Business</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Trending</a>
                                        <ul class="menu-items">
                                            <li><a href="#" class="menu-item">Inovacion</a></li>
                                            <li><a href="#" class="menu-item">Tecnologia</a></li>
                                            <li><a href="#" class="menu-item">Creatividad</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Eventos</a>
                                        <ul class="menu-items">
                                            <li><a href="#" class="menu-item">Social Media S</a></li>
                                            <li><a href="#" class="menu-item">EXMA</a></li>
                                            <li><a href="#" class="menu-item">Trendshoper</a></li>
                                            <li><a href="#" class="menu-item">Festival el Locoto</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Tools</a>
                                    </li>
                                    <li><a href="#" class="menu-padre">Subscripcion</a>
                                        <ul class="menu-items">
                                            <li><a href="#" class="menu-item">Impresa</a></li>
                                            <li><a href="#" class="menu-item">Newsletter</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Pauta</a>
                                    </li>
                                    <li><a href="#" class="menu-padre">BookMall</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-2 col-md-10">
                            <div class=" menu-nav">
                                fb tw g+
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</section>

<div class="menu-container" style="display: none">
    <img class="logo" alt="logo" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
    <a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars" aria-hidden="true"></i></a>
</div>
<section id="intro">
    <div class="intro-slicks">
        <div class="slick-item">
            <object id="svg-0" class="svg-object" type="image/svg+xml" data="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/icon_m.svg"></object>
            <img class="intro-bg" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/photo01.jpg" alt="imagen"/>
        </div>
        <div class="slick-item">
            <object id="svg-1" class="svg-object" type="image/svg+xml" data="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/icon_k.svg"></object>
            <img class="intro-bg" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/photo03.jpg" alt="imagen"/>
        </div>
        <div class="slick-item">
            <object id="svg-2" class="svg-object" type="image/svg+xml" data="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/icon_t.svg"></object>
            <img class="intro-bg" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/photo05.jpg" alt="imagen"/>
        </div>
    </div>
    <img class="intro-logo" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo.png" alt="logo"/>
</section>

<section id="bienvenido">
    <img class="logo" alt="logo" src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
    <h2>Bienvenido!</h2>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur
    </p>
    <a href="#">Ver más</a>
</section>
</body>

<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<?php
echo Com_Helper_Script::getInstance();
?>

</html>