<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Perfil</title>
        <link href="http://www.douglasvillarroel.com" hreflang="es" rel="alternate" title="CNN Mexico" type="text/html"/>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="all">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;"> 
       
        <link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
        <?PHP
        //Adding Css
        Com_Helper_Style::getInstance()->addFile("Public/font-awesome.min.css")
                ->addFile("Public/style.css")
                ->addFile("Public/ModalBorder.css")
                ->addFile("Public/jBox.css")
                //->addFile("Public/account.css")
                ->addFile("Public/login.css")
                ->addFile("Public/datepicker.css")
                ->addFile("Public/sweetalert.css");

        echo Com_Helper_Style::getInstance();
        ?>
    </head>
    <body class="login">

        <div class="clear"></div>
        <?PHP
        $this->getContent();
        ?>
        

        <div class="modal" id="loading">
            <img src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/loading.gif" width="48px"/>
        </div>

        

        <?PHP
        //Adding Javascript
        Com_Helper_Script::getInstance()->addFile("Public/jquery.1.11.1.min.js")
                ->addFile("Public/jquery.jbox.min.js")                
                ->addFile("Public/jquery.datepicker.js")                
                ->addFile("Public/login.js")
                ->addFile("Public/sweetalert.min.js");
               

        echo Com_Helper_Script::getInstance();
        ?>
       
    </body>
</html>