<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Perfil - <?PHP echo Configurations_Helper_Configuration::getInstance()->getKey("PAGE_TITLE"); ?></title>
        <link href="http://www.douglasvillarroel.com" hreflang="es" rel="alternate" title="CNN Mexico" type="text/html"/>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="robots" content="all">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;"> 
        <link type="image/x-icon" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicon.ico" rel="shortcut icon">
        <link type="image/x-icon" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicon.ico" rel="icon">

        <!--Metatags-->
        <meta name="title" content="<?PHP echo $this->new->NewTitle; ?> - <?PHP echo Configurations_Helper_Configuration::getInstance()->getKey("PAGE_TITLE"); ?>">
        <meta name="keywords" content="<?PHP echo $this->new->NewTags; ?>">
        <meta name="description" content="<?PHP echo $this->new->NewTitle; ?> , <?PHP echo $this->new->NewTags; ?>">

        <!--Facebook Tags-->
        <meta property="fb:app_id" contents="131569326876024"/>
        <meta property="og:title" content="<?PHP echo $this->new->NewTitle; ?> - <?PHP echo Configurations_Helper_Configuration::getInstance()->getKey("PAGE_TITLE"); ?>"/>
        <meta property="og:description" content="<?PHP echo $this->new->NewTitle; ?> , <?PHP echo $this->new->NewTags; ?>">
        <meta property="og:site_name" content="<?PHP echo Configurations_Helper_Configuration::getInstance()->getKey("PAGE_TITLE"); ?>"/>
        <meta property="og:url" content="<?PHP echo Com_Helper_Url::getInstance()->urlBase . '/article/' . $this->new->NewUrl; ?>"/>
        <meta property="og:image" content="<?PHP echo Com_Helper_Url::getInstance()->getResources(); ?>/Uploads/Image/<?PHP echo $this->new->NewImage; ?>"/>
        <link href='http://fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
        <?PHP
        //Adding Css
        Com_Helper_Style::getInstance()->addFile("Public/font-awesome.min.css")
                ->addFile("Public/style.css")
                ->addFile("Public/ModalBorder.css")
                ->addFile("Public/jBox.css")
                ->addFile("Public/account.css")
                ->addFile("Public/login.css")
                ->addFile("Public/datepicker.css");

        echo Com_Helper_Style::getInstance();
        ?>
    </head>
    <body class="login">

        <img id="sup" src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/sup.png">
        <img id="inf" src="<?= Com_Helper_Url::getInstance()->getImage(); ?>/Public/inferior.png">
        <div class="clear"></div>
        <?PHP
        $this->getContent();
        ?>
        

        <div class="modal" id="loading">
            <img src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/loading.gif" width="48px"/>
        </div>

        

        <?PHP
        //Adding Javascript
        Com_Helper_Script::getInstance()->addFile("Public/jquery.1.11.1.min.js")
                ->addFile("Public/jquery.jbox.min.js")                
                ->addFile("Public/jquery.datepicker.js")                
                ->addFile("Public/login.js");
               

        echo Com_Helper_Script::getInstance();
        ?>
        <script type="text/javascript">
            setUrlBase('<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>');
        </script>
    </body>
</html>