<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>MARKETING NEWS- notas</title>
    <style>
        body {
            padding: 0;
            margin: 0
        }

        #preload {
            position: absolute;
            width: 100%;
            height: 100vh;
            z-index: 9000;
            background: white;
        }

        #preloader {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }

        .preloader-item {
            width: 80px;
            height: 80px;
            margin: 10px;
            background: #CCCCCC;
            border-radius: 10px;
            float: left;
            display: block;
        }

        .preloader-item1 {
            animation-name: pulse;
            animation-duration: 1.5s;
            animation-delay: 0.3s;
            animation-iteration-count: infinite;
        }

        .preloader-item2 {
            animation-name: pulse;
            animation-duration: 1.5s;
            animation-delay: 0.6s;
            animation-iteration-count: infinite;
        }

        .preloader-item3 {
            animation-name: pulse;
            animation-duration: 1.5s;
            animation-delay: 0.9s;
            animation-iteration-count: infinite;
        }

        @keyframes pulse {
            0% {
                background-color: #941b80;
            }
            33% {
                background-color: #e5007e;
            }
            66% {
                background-color: #e20613;
            }
            100% {
                background-color: #941b80;
            }
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="resources/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="resources/font-awesome.css"/>
    <link rel="stylesheet" type="text/css" href="resources/slick.css"/>
    <link rel="stylesheet" type="text/css" href="resources/slick.css"/>
    <link rel="stylesheet" type="text/css" href="resources/slick-theme.css"/>
    <link rel="stylesheet" type="text/css" href="resources/swiper.css"/>
    <link rel="stylesheet" type="text/css" href="resources/animate.css"/>
    <link rel="stylesheet" type="text/css" href="resources/owl.carousel.css"/>
    <link rel="stylesheet" type="text/css" href="resources/materialicon.css"/>
    <!--<link rel="stylesheet" type="text/css" href="resources/owl.theme.css"/>-->
    <!--<link rel="stylesheet" type="text/css" href="resources/owl.transitions.css"/>-->
    <link rel="stylesheet" type="text/css" href="resources/font-awesome-4.6.3/css/font-awesome.min.css"/>


    <link rel="stylesheet" type="text/css" href="resources/marketing-intro.css"/>
    <link rel="stylesheet" type="text/css" href="resources/marketing-header.css"/>

    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="resources/bootstrap.js"></script>
    <script type="text/javascript" src="resources/slick.min.js"></script>
    <script type="text/javascript" src="resources/pathformer.js"></script>
    <script type="text/javascript" src="resources/vivus.js"></script>
    <script type="text/javascript" src="resources/owl.carousel.min.js"></script>
    <script type="text/javascript" src="resources/marketing.js"></script>

    <script type="text/javascript" src="resources/rdcalendar.js"></script>
    <script type="text/javascript" src="resources/swiper.jquery.js"></script>
</head>
<body class="desktop">
<section id="preload">
    <div id="preloader">
        <div class="preloader-item preloader-item1"></div>
        <div class="preloader-item preloader-item2"></div>
        <div class="preloader-item preloader-item3"></div>
    </div>
</section>

<section class="main-menu">
    <div class="container-fluid">
        <div class="row">
            <div class="menu-content col-md-6">
                <div class="menu-container" style="display: none">
                    <img class="logo" alt="logo" src="imagenes/marketing-logo-small.png">
                    <a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars"
                                                                            aria-hidden="true"></i></a>
                </div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-2">
                            <div class="menu-cerrar">
                                <a href="javascript:void(0)" onclick="toogleMenu();"> <i class="fa fa-close"></i></a>
                            </div>
                        </div>
                        <div class="col-md-10">
                            <div class=" menu-nav">
                                <ul>
                                    <li><a href="#" class="menu-padre active">mkt</a>
                                        <ul class="menu-items active">
                                            <li class="active"><a href="#" class="menu-item">Brand</a></li>
                                            <li><a href="#" class="menu-item">Publicidad</a></li>
                                            <li><a href="#" class="menu-item">Social Business</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Trending</a>
                                        <ul class="menu-items">
                                            <li><a href="#" class="menu-item">Inovacion</a></li>
                                            <li><a href="#" class="menu-item">Tecnologia</a></li>
                                            <li><a href="#" class="menu-item">Creatividad</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Eventos</a>
                                        <ul class="menu-items">
                                            <li><a href="#" class="menu-item">Social Media S</a></li>
                                            <li><a href="#" class="menu-item">EXMA</a></li>
                                            <li><a href="#" class="menu-item">Trendshoper</a></li>
                                            <li><a href="#" class="menu-item">Festival el Locoto</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Tools</a>
                                    </li>
                                    <li><a href="#" class="menu-padre">Subscripcion</a>
                                        <ul class="menu-items">
                                            <li><a href="#" class="menu-item">Impresa</a></li>
                                            <li><a href="#" class="menu-item">Newsletter</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#" class="menu-padre">Pauta</a>
                                    </li>
                                    <li><a href="#" class="menu-padre">BookMall</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-offset-2 col-md-10">
                            <div class=" menu-nav">
                                fb tw g+
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="menu-container" style="display: none">
    <img class="logo" alt="logo" src="imagenes/marketing-logo-small.png">
    <a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars" aria-hidden="true"></i></a>
</div>

<section class="section-sm-60">
    <div class="container container-mod-1">
        <div class="row row-no-gutter">
            <!--CONTENIODO PAGINA-->
             <?PHP
            $this->getContent();
            ?>
            <div class="side-right col-xs-12 col-md-4">
                <!--Sidebar-->
                <div class="sidebar offset-top-40 offset-md-top-0">
                    <div class="sidebar-module  module-search bg-darker text-left">
                        <h5>Busqueda</h5>
                        <!-- RD Navbar Search-->
                        <div class="rd-navbar-search-mod-1">
                            <form class="form-inline-flex-xs">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" id="exampleInputAmount"
                                               placeholder="buscar">

                                        <div class="input-group-addon">
                                            <button type="submit" class="btn"><i class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                    <div class="sidebar-module sidebar-module-mod-1 text-center height-615"
                         style="background-image: url(imagenes/picture01.jpg);background-size: cover;">
                    </div>
                    <div class="sidebar-module module-social bg-primary text-left">
                        <h5>Social</h5>
                        <ul class="list-inline">
                            <li><a href="#" class="icon icon-sm icon-white icon-circle icon-border fa fa-facebook"></a>
                            </li>
                            <li><a href="#" class="icon icon-sm icon-white icon-circle icon-border fa fa-twitter"></a>
                            </li>
                            <li><a href="#"
                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-google-plus"></a></li>
                        </ul>
                    </div>
                    <div class="sidebar-module module-newsletter bg-darker text-left">
                        <h5>Newsletter</h5>

                        <p>Enter your email below and be the first to get makeup news!</p>
                        <!-- Rd Mailform result field-->
                        <div class="rd-mailform-validate"></div>
                        <form data-result-class="rd-mailform-validate" data-form-type="subscribe" method="post"
                              action="bat/rd-mailform.php" class="rd-mailform subscribe text-left offset-top-30">
                            <input type="text" name="email" data-constraints="@NotEmpty @Email"
                                   placeholder="Your e-mail">
                            <button class="btn btn-transparent btn-sm">subscribe</button>
                        </form>
                    </div>
                    <div class="sidebar-module">
                        <div class="banner-block"><img src="imagenes/publicidad01.png" alt=""></div>
                    </div>

                    <div class="sidebar-module bg-gray text-left">
                        <h5>Calendar</h5>
                        <!-- RD Calendar-->
                        <div class="rd-calendar">
                            <div class="rdc-panel">
                                <div class="rdc-month"></div>
                                <div class="rdc-fullyear"></div>
                                <a class="rdc-next">
                                    <i class="fa fa-arrow-right"
                                       style="font-size: 16px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;"></i>
                                </a>
                                <a class="rdc-prev">
                                    <i class="fa fa-arrow-left"
                                       style="font-size: 16px;display: inline-block;text-align: center;vertical-align: middle;transition: .4s;"></i>
                                </a>
                            </div>
                            <div class="rdc-table"></div>
                        </div>
                    </div>

                    <div class="sidebar-module  bg-gray module-suscribe-magazine text-left">
                        <h5>Suscribete</h5>

                        <div class="magazine-container">
                            <img src="imagenes/magazine01.jpg" alt=""/>
                        </div>
                        <div class="magazine-container-decoration"></div>

                        <form class="form-inline-flex-xs">
                            <div class="form-group">
                                <input type="text" class="form-control" id="nombre" placeholder="nombre">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" id="apellido" placeholder="epallido">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-block">Suscribete!</button>
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-module module-pauta text-left">
                        <h3>Pauta</h3>
                        <div class="pauta-container">
                            <div class="pauta-item">
                                <a href="#" class="tag bg-pink">Revista</a>
                                <h4>Titulo lorem ipsum</h4>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit din dignissim.
                                    Pellee habitant morbi trisque Lorem ipsum dolor sit amet, consectetur adipiscing
                                    elit. Sed blandit din dignissim. Pellee habitant morbi trisque...
                                </p>
                            </div>
                            <div class="pauta-item">
                                <a href="#" class="tag bg-punch">WEB</a>
                                <h4>Titulo lorem ipsum</h4>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit din dignissim.
                                    Pellee habitant morbi trisque Lorem ipsum dolor sit amet, consectetur adipiscing
                                    elit. Sed blandit din dignissim. Pellee habitant morbi trisque...
                                </p>
                            </div>
                            <div class="pauta-item">
                                <a href="#" class="tag bg-info">Revista</a>
                                <h4>Titulo lorem ipsum</h4>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed blandit din dignissim.
                                    Pellee habitant morbi trisque Lorem ipsum dolor sit amet, consectetur adipiscing
                                    elit. Sed blandit din dignissim. Pellee habitant morbi trisque...
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="insta-wrap">
    <div class="insta-btn-wrap bg-chambray"><a href="#">Follow on <br class="visible-lg">Instagram</a></div>
    <!-- RD Instafeed-->
    <div data-instafeed-clientid="44f19408f04040bd85214315861a84a1" data-instafeed-get="user"
         data-instafeed-user="499522078" data-items="2" data-sm-items="5" data-lg-items="9" data-loop="false"
         data-nav="true" class="owl-carousel instafeed element-groups-xs-custom">
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed03.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank"
               class="img-thumbnail-variant-3"><img
                    src="imagenes/feed01.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed02.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed03.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank"
               class="img-thumbnail-variant-3"><img
                    src="imagenes/feed01.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed02.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed03.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank"
               class="img-thumbnail-variant-3"><img
                    src="imagenes/feed01.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed02.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed03.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank"
               class="img-thumbnail-variant-3"><img
                    src="imagenes/feed01.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed02.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed03.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank"
               class="img-thumbnail-variant-3"><img
                    src="imagenes/feed01.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
        <div data-instafeed-item="" class="owl-item insta-item">
            <a href="#" data-link="href" target="_blank" class="img-thumbnail-variant-3">
                <img src="imagenes/feed02.jpg" alt="" data-images-thumbnail-url="src" width="192" height="192">
            </a>
        </div>
    </div>
</section>
<section>
    <div class="container-fluid">
        <div class="row text-center">
            <div class="go-up">
                <i class="fa fa-angle-up icon-white"></i>
            </div>
        </div>
    </div>
</section>
<section class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4 col-footer color-gray-1">
                <h2>Navegar</h2>
                <ul>
                    <li><a href="#"> Contacto</a></li>
                    <li><a href="#"> Escribe para nos.</a></li>
                    <li><a href="#"> Kit de ventas</a></li>
                </ul>
            </div>
            <div class="col-sm-4 col-footer color-gray-2">
                <h2>Social</h2>
                <ul>
                    <li><a href="#"> Facebook</a></li>
                    <li><a href="#"> Twitter</a></li>
                    <li><a href="#"> Google +</a></li>
                </ul>
            </div>
            <div class="col-sm-4 text-center col-footer color-gray-1">
                <img class="logo img-responsive" src="imagenes/logo_black.png" alt=""/>

                <p class="copy">    &copy; 2016</p>
            </div>
        </div>
    </div>
</section>
<script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        direction: 'vertical',
        slidesPerView: 1,
        paginationClickable: true,
        spaceBetween: 30,
        autoplay: 8000,
        mousewheelControl: false,
        onTransitionStart: function (swiper) {
            toggleSwiperInnerVideos(swiper);
        },
        onTransitionEnd: function (swiper) {
            toggleSwiperCaptionAnimation(swiper);
        },
        onInit: function (swiper) {
            toggleSwiperInnerVideos(swiper);
            toggleSwiperCaptionAnimation(swiper);
//            var swiperParalax = s.find(".swiper-parallax");

//            for (var k = 0; k < swiperParalax.length; k++) {
//                var $this = $(swiperParalax[k]),
//                        speed;
//
//                if (parallax && !isIEBrows && !isMobile) {
//                    if (speed = $this.attr("data-speed")) {
//                        makeParallax($this, speed, s, false);
//                    }
//                }
//            }
            $(window).on('resize', function () {
                swiper.update(true);
            })
        }
    });
    function toggleSwiperInnerVideos(swiper) {
        var prevSlide = $(swiper.slides[swiper.previousIndex]),
                nextSlide = $(swiper.slides[swiper.activeIndex]),
                videos;

        prevSlide.find("video").each(function () {
            this.pause();
        });

        videos = nextSlide.find("video");
        if (videos.length) {
            videos.get(0).play();
        }
    }

    function toggleSwiperCaptionAnimation(swiper) {
        var prevSlide = $(swiper.container),
                nextSlide = $(swiper.slides[swiper.activeIndex]);

        prevSlide
                .find("[data-caption-animate]")
                .each(function () {
                    var $this = $(this);
                    $this
                            .removeClass("animated")
                            .removeClass($this.attr("data-caption-animate"))
                            .addClass("not-animated");
                });

        nextSlide
                .find("[data-caption-animate]")
                .each(function () {
                    var $this = $(this),
                            delay = $this.attr("data-caption-delay");

                    setTimeout(function () {
                        $this
                                .removeClass("not-animated")
                                .addClass($this.attr("data-caption-animate"))
                                .addClass("animated");
                    }, delay ? parseInt(delay) : 0);
                });
    }

    var owls = $('.owl-carousel');
    if (owls.length) {
        for (i = 0; i < owls.length; i++) {

            var c = $(owls[i]),
                    responsive = {};

            var aliaces = ["-", "-xs-", "-sm-", "-md-", "-lg-"],
                    values = [0, 480, 768, 992, 1200],
                    j, k;

            for (j = 0; j < values.length; j++) {
                responsive[values[j]] = {};
                for (k = j; k >= -1; k--) {
                    if (!responsive[values[j]]["items"] && c.attr("data" + aliaces[k] + "items")) {
                        responsive[values[j]]["items"] = k < 0 ? 1 : parseInt(c.attr("data" + aliaces[k] + "items"));
                    }
                    if (!responsive[values[j]]["stagePadding"] && responsive[values[j]]["stagePadding"] !== 0 && c.attr("data" + aliaces[k] + "stage-padding")) {
                        responsive[values[j]]["stagePadding"] = k < 0 ? 0 : parseInt(c.attr("data" + aliaces[k] + "stage-padding"));
                    }
                    if (!responsive[values[j]]["margin"] && responsive[values[j]]["margin"] !== 0 && c.attr("data" + aliaces[k] + "margin")) {
                        responsive[values[j]]["margin"] = k < 0 ? 30 : parseInt(c.attr("data" + aliaces[k] + "margin"));
                    }
                }
            }

            c.owlCarousel({
                autoplay: c.attr("data-autoplay") === "true",
                loop: c.attr("data-loop") !== "false",
                items: 1,
                dotsContainer: c.attr("data-pagination-class") || false,
                navContainer: c.attr("data-navigation-class") || false,
                mouseDrag: c.attr("data-mouse-drag") !== "false",
//                nav: c.attr("data-nav") === "true",
                nav: "true",
//                dots: c.attr("data-dots") === "true",
//                dotsEach: c.attr("data-dots-each") ? parseInt(c.attr("data-dots-each")) : false,
                responsive: responsive,
                navText: [],
                onInitialized: function () {
                    if ($.fn.magnificPopup) {
                        var o = this.$element.attr('data-lightbox') !== undefined && this.$element.attr("data-lightbox") !== "gallery",
                                g = this.$element.attr('data-lightbox') === "gallery";
                        if (o) {
                            for (var m = 0; m < (this.$element).length; m++) {
                                var $this = $(this.$element[m]);
                                $this.magnificPopup({
                                    type: $this.attr("data-lightbox"),
                                    callbacks: {
                                        open: function () {
                                            if (isTouch) {
                                                $document.on("touchmove", preventScroll);
                                                $document.swipe({
                                                    swipeDown: function () {
                                                        $.magnificPopup.close();
                                                    }
                                                });
                                            }
                                        },
                                        close: function () {
                                            if (isTouch) {
                                                $document.off("touchmove", preventScroll);
                                                $document.swipe("destroy");
                                            }
                                        }
                                    }
                                });
                            }
                        }
                        if (g) {
                            for (var k = 0; k < (this.$element).length; k++) {
                                var $gallery = $(this.$element[k]).find('[data-lightbox]');
                                for (var j = 0; j < $gallery.length; j++) {
                                    var $item = $gallery[j];
                                    $item.addClass("mfp-" + $item.attr("data-lightbox"));
                                }
                                $gallery.end()
                                        .magnificPopup({
                                            delegate: '.owl-item [data-lightbox]',
                                            type: "image",
                                            gallery: {
                                                enabled: true
                                            },
                                            callbacks: {
                                                open: function () {
                                                    if (isTouch) {
                                                        $document.on("touchmove", preventScroll);
                                                        $document.swipe({
                                                            swipeDown: function () {
                                                                $.magnificPopup.close();
                                                            }
                                                        });
                                                    }
                                                },
                                                close: function () {
                                                    if (isTouch) {
                                                        $document.off("touchmove", preventScroll);
                                                        $document.swipe("destroy");
                                                    }
                                                }
                                            }
                                        });
                            }
                        }
                    }
                    if (c.attr("data-active")) {
                        c.trigger("to.owl.carousel", c.attr("data-active") - 1);
                    }
                }
            });
        }
    }

    $('.rd-calendar').rdCalendar({
        days: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
        months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
    });

    $('.pauta-container').slick({
        dots: false,
        infinite: true,
        arrows: true,
        slidesToShow: 1,
        slidesToScroll: 1,
        autoplay: false,
        autoplaySpeed: 3000
    });


</script>
</body>
</html>