<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">
        <title>MARKETING NEWS</title>
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel='stylesheet' id='open-sans-css'
              href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.1'
              type='text/css' media='all'/>
        <link
            href="//fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,700,800%7CPlayfair+Display:400,400italic,700,900&amp;subset=greek,latin,latin"
            rel="stylesheet" type="text/css">


        <!-- Fav and Touch Icons -->       

        <link rel="apple-touch-icon" sizes="180x180" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/apple-touch-icon.png">
        <link rel="icon" type="image/png" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-32x32.png" sizes="32x32">
        <link rel="icon" type="image/png" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon-16x16.png" sizes="16x16">
        <link rel="manifest" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/manifest.json">
        <link rel="mask-icon" href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/safari-pinned-tab.svg" color="#5bbad5">
        <link rel="shortcut icon"
              href="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/favicons/favicon.ico"
              type="image/x-icon"/>

        <style>
            body {
                padding: 0;
                margin: 0
            }

            #preload {
                position: absolute;
                width: 100%;
                height: 100vh;
                z-index: 9000;
                background: white;
            }

            #preloader {
                position: absolute;
                left: 50%;
                top: 50%;
                transform: translate(-50%, -50%);
            }

            .preloader-item {
                width: 80px;
                height: 80px;
                margin: 10px;
                background: #CCCCCC;
                border-radius: 10px;
                float: left;
                display: block;
            }

            .preloader-item1 {
                animation-name: pulse;
                animation-duration: 1.5s;
                animation-delay: 0.3s;
                animation-iteration-count: infinite;
            }

            .preloader-item2 {
                animation-name: pulse;
                animation-duration: 1.5s;
                animation-delay: 0.6s;
                animation-iteration-count: infinite;
            }

            .preloader-item3 {
                animation-name: pulse;
                animation-duration: 1.5s;
                animation-delay: 0.9s;
                animation-iteration-count: infinite;
            }

            @keyframes pulse {
                0% {
                    background-color: #941b80;
                }
                33% {
                    background-color: #e5007e;
                }
                66% {
                    background-color: #e20613;
                }
                100% {
                    background-color: #941b80;
                }
            }
        </style>

        <?PHP
        Com_Helper_Style::getInstance()
                ->addFile("Public/bootstrap.css")
                ->addFile("Public/font-awesome.css")
                ->addFile("Public/slick.css")
                ->addFile("Public/slick-theme.css")
                ->addFile("Public/swiper.css")
                ->addFile("Public/animate.css")
                ->addFile("Public/owl.carousel.css")
                ->addFile("Public/materialicon.css")
                ->addFile("Public/marketing-intro.css")
                ->addFile("Public/jquery.fancybox.css");

        echo Com_Helper_Style::getInstance();
        ?>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <?php
        Com_Helper_Script::getInstance()
                ->addFile("Public/jquery.js")
                ->addFile("Public/bootstrap.js")
                ->addFile("Public/slick.min.js")
                ->addFile("Public/pathformer.js")
                ->addFile("Public/vivus.js")
                ->addFile("Public/owl.carousel.js")
                ->addFile("Public/marketing.js")
                ->addFile("Public/rdcalendar.js")
                ->addFile("Public/swiper.jquery.js")
                ->addFile("Public/jquery.fancybox.js")
                ->addFile("Public/login.js");

        echo Com_Helper_Script::getInstance();
        ?>
    </head>

    <body class="desktop">
        <section id="preload">
            <div id="preloader">
                <div class="preloader-item preloader-item1"></div>
                <div class="preloader-item preloader-item2"></div>
                <div class="preloader-item preloader-item3"></div>
            </div>
        </section>

        <section class="main-menu">
            <div class="container-fluid">
                <div class="row">
                    <div class="menu-content col-md-6">
                        <div class="menu-container" style="display: none">

                            <img class="logo" alt="logo"
                                 src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
                            <a href="javascript:void(0)" onclick="toogleMenu();">
                                <i class="fa fa-close" aria-hidden="true"></i>
                            </a>
                        </div>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="menu-nav">
                                        <ul>
                                            <?PHP Menu_Widget_Menu::getInstance()->setLan($this->lan)->setParent(1)->render(); ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="rowgit ">
                                <div class="col-md-12">
                                    <div class="menu-redes">
                                        <ul class="list-inline">
                                            <li><a target="_blank"
                                                   href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkFacebook')->LinUrl; ?>"
                                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-facebook"></a>
                                            </li>
                                            <li><a target="_blank"
                                                   href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkTwitter')->LinUrl; ?>"
                                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-twitter"></a>
                                            </li>
                                            <li><a target="_blank"
                                                   href="<?PHP echo Links_Helper_Link::getInstance()->get('LinkInstagram')->LinUrl; ?>"
                                                   class="icon icon-sm icon-white icon-circle icon-border fa fa-instagram"></a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="row hidden">
                                <div class="col-md-offset-2 col-md-10">
                                    <div class=" menu-nav">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="menu-container" style="display: none">
            <img class="logo" alt="logo"
                 src="<?PHP echo Com_Helper_Url::getInstance()->getImage(); ?>/Public/marketing-logo-small.png">
            <a href="javascript:void(0)" onclick="toogleMenu();"><i class="fa fa-bars"
                                                                    aria-hidden="true"></i></a>
        </div>

        <section class="section-sm-60">
            <div class="container container-mod-1">
                <div class="row row-no-gutter">
                    <!--CONTENIODO PAGINA-->
                    <?PHP
                    $this->getContent();
                    ?>

                </div>
            </div>
        </section>
        <section class="insta-wrap">
            <?php Public_Widget_FollowInstagram::getInstance()->setLan($this->lan)->render(); ?>
        </section>
        <?php Public_Widget_Footer::getInstance()->setLan($this->lan)->render(); ?>
        <script>
            var swiper = new Swiper('.swiper-container', {
                pagination: '.swiper-pagination',
                direction: 'vertical',
                slidesPerView: 1,
                paginationClickable: true,
                spaceBetween: 30,
                autoplay: 8000,
                mousewheelControl: false,
                onTransitionStart: function (swiper) {
                    toggleSwiperInnerVideos(swiper);
                },
                onTransitionEnd: function (swiper) {
                    toggleSwiperCaptionAnimation(swiper);
                },
                onInit: function (swiper) {
                    toggleSwiperInnerVideos(swiper);
                    toggleSwiperCaptionAnimation(swiper);
                    //            var swiperParalax = s.find(".swiper-parallax");

                    //            for (var k = 0; k < swiperParalax.length; k++) {
                    //                var $this = $(swiperParalax[k]),
                    //                        speed;
                    //
                    //                if (parallax && !isIEBrows && !isMobile) {
                    //                    if (speed = $this.attr("data-speed")) {
                    //                        makeParallax($this, speed, s, false);
                    //                    }
                    //                }
                    //            }
                    $(window).on('resize', function () {
                        swiper.update(true);
                    })
                }
            });
            function toggleSwiperInnerVideos(swiper) {
                var prevSlide = $(swiper.slides[swiper.previousIndex]),
                        nextSlide = $(swiper.slides[swiper.activeIndex]),
                        videos;

                prevSlide.find("video").each(function () {
                    this.pause();
                });

                videos = nextSlide.find("video");
                if (videos.length) {
                    videos.get(0).play();
                }
            }

            function toggleSwiperCaptionAnimation(swiper) {
                var prevSlide = $(swiper.container),
                        nextSlide = $(swiper.slides[swiper.activeIndex]);

                prevSlide
                        .find("[data-caption-animate]")
                        .each(function () {
                            var $this = $(this);
                            $this
                                    .removeClass("animated")
                                    .removeClass($this.attr("data-caption-animate"))
                                    .addClass("not-animated");
                        });

                nextSlide
                        .find("[data-caption-animate]")
                        .each(function () {
                            var $this = $(this),
                                    delay = $this.attr("data-caption-delay");

                            setTimeout(function () {
                                $this
                                        .removeClass("not-animated")
                                        .addClass($this.attr("data-caption-animate"))
                                        .addClass("animated");
                            }, delay ? parseInt(delay) : 0);
                        });
            }

            var owls = $('.owl-carousel');
            if (owls.length) {
                for (i = 0; i < owls.length; i++) {

                    var c = $(owls[i]),
                            responsive = {};

                    var aliaces = ["-", "-xs-", "-sm-", "-md-", "-lg-"],
                            values = [0, 480, 768, 992, 1200],
                            j, k;

                    for (j = 0; j < values.length; j++) {
                        responsive[values[j]] = {};
                        for (k = j; k >= -1; k--) {
                            if (!responsive[values[j]]["items"] && c.attr("data" + aliaces[k] + "items")) {
                                responsive[values[j]]["items"] = k < 0 ? 1 : parseInt(c.attr("data" + aliaces[k] + "items"));
                            }
                            if (!responsive[values[j]]["stagePadding"] && responsive[values[j]]["stagePadding"] !== 0 && c.attr("data" + aliaces[k] + "stage-padding")) {
                                responsive[values[j]]["stagePadding"] = k < 0 ? 0 : parseInt(c.attr("data" + aliaces[k] + "stage-padding"));
                            }
                            if (!responsive[values[j]]["margin"] && responsive[values[j]]["margin"] !== 0 && c.attr("data" + aliaces[k] + "margin")) {
                                responsive[values[j]]["margin"] = k < 0 ? 30 : parseInt(c.attr("data" + aliaces[k] + "margin"));
                            }
                        }
                    }

                    c.owlCarousel({
                        autoplay: c.attr("data-autoplay") === "true",
                        loop: c.attr("data-loop") !== "false",
                        items: 1,
                        dotsContainer: c.attr("data-pagination-class") || false,
                        navContainer: c.attr("data-navigation-class") || false,
                        mouseDrag: c.attr("data-mouse-drag") !== "false",
                        //                nav: c.attr("data-nav") === "true",
                        nav: "true",
                        //                dots: c.attr("data-dots") === "true",
                        //                dotsEach: c.attr("data-dots-each") ? parseInt(c.attr("data-dots-each")) : false,
                        responsive: responsive,
                        navText: [],
                        onInitialized: function () {
                            if ($.fn.magnificPopup) {
                                var o = this.$element.attr('data-lightbox') !== undefined && this.$element.attr("data-lightbox") !== "gallery",
                                        g = this.$element.attr('data-lightbox') === "gallery";
                                if (o) {
                                    for (var m = 0; m < (this.$element).length; m++) {
                                        var $this = $(this.$element[m]);
                                        $this.magnificPopup({
                                            type: $this.attr("data-lightbox"),
                                            callbacks: {
                                                open: function () {
                                                    if (isTouch) {
                                                        $document.on("touchmove", preventScroll);
                                                        $document.swipe({
                                                            swipeDown: function () {
                                                                $.magnificPopup.close();
                                                            }
                                                        });
                                                    }
                                                },
                                                close: function () {
                                                    if (isTouch) {
                                                        $document.off("touchmove", preventScroll);
                                                        $document.swipe("destroy");
                                                    }
                                                }
                                            }
                                        });
                                    }
                                }
                                if (g) {
                                    for (var k = 0; k < (this.$element).length; k++) {
                                        var $gallery = $(this.$element[k]).find('[data-lightbox]');
                                        for (var j = 0; j < $gallery.length; j++) {
                                            var $item = $gallery[j];
                                            $item.addClass("mfp-" + $item.attr("data-lightbox"));
                                        }
                                        $gallery.end()
                                                .magnificPopup({
                                                    delegate: '.owl-item [data-lightbox]',
                                                    type: "image",
                                                    gallery: {
                                                        enabled: true
                                                    },
                                                    callbacks: {
                                                        open: function () {
                                                            if (isTouch) {
                                                                $document.on("touchmove", preventScroll);
                                                                $document.swipe({
                                                                    swipeDown: function () {
                                                                        $.magnificPopup.close();
                                                                    }
                                                                });
                                                            }
                                                        },
                                                        close: function () {
                                                            if (isTouch) {
                                                                $document.off("touchmove", preventScroll);
                                                                $document.swipe("destroy");
                                                            }
                                                        }
                                                    }
                                                });
                                    }
                                }
                            }
                            if (c.attr("data-active")) {
                                c.trigger("to.owl.carousel", c.attr("data-active") - 1);
                            }
                        }
                    });
                }
            }

            $('.rd-calendar').rdCalendar({
                days: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
                months: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
            });

            $('.pauta-container').slick({
                dots: false,
                infinite: true,
                arrows: true,
                slidesToShow: 1,
                slidesToScroll: 1,
                autoplay: false,
                autoplaySpeed: 3000
            });


        </script>
    </body>
</html>