<!DOCTYPE html>
<html>
<head>

    <!-- Title -->
    <title><?PHP echo CMS_TITLE; ?></title>

    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta charset="UTF-8">
    <meta name="description" content="CMS Hotel Cortez"/>
    <meta name="keywords" content=""/>
    <meta name="author" content="Qwerty Bolivia"/>

    <!-- Styles -->

    <?PHP
    Com_Helper_Style::getInstance()->addFile("Admin/plugins/pace-master/themes/blue/pace-theme-flash.css")
        ->addFile("Admin/plugins/uniform/css/uniform.default.min.css")
        ->addFile("Admin/plugins/bootstrap/css/bootstrap.min.css")
        ->addFile("Admin/datepicker.css")
        ->addFile("Admin/jquery.ui.css")
        ->addFile("Admin/admin.css")
        ->addFile("Admin/editor.css")
        ->addFile("Admin/codemirror.css")
        ->addFile("Admin/jBox.css")
        ->addFile("Admin/plugins/fontawesome/css/font-awesome.css")
        ->addFile("Admin/plugins/line-icons/simple-line-icons.css")
        ->addFile("Admin/plugins/offcanvasmenueffects/css/menu_cornerbox.css")
        ->addFile("Admin/plugins/waves/waves.min.css")
        ->addFile("Admin/plugins/switchery/switchery.min.css")
        ->addFile("Admin/plugins/3d-bold-navigation/css/style.css")
        ->addFile("Admin/plugins/slidepushmenus/css/component.css")
        ->addFile("Admin/plugins/weather-icons-master/css/weather-icons.min.css")
        ->addFile("Admin/plugins/switchery/switchery.min.css")
        ->addFile("Admin/plugins/metrojs/MetroJs.min.css")
        ->addFile("Admin/plugins/toastr/toastr.min.css")
        ->addFile("Admin/modern.css")
        ->addFile("Admin/themes/white.css")
        ->addFile("Admin/custom.css");

    echo Com_Helper_Style::getInstance();
    ?>

    

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="page-header-fixed">
<div class="overlay"></div>


<div class="menu-wrap">
    <nav class="profile-menu">
        <div class="profile"><img
                src="<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo get('userPhoto'); ?>"
                width="52" alt="<?php echo get('userFullName'); ?>"/><span><?php echo get('userFullName'); ?></span></div>
        <div class="profile-menu-list">
            <a href="#"><i class="fa fa-star"></i><span>Favorites</span></a>
            <a href="#"><i class="fa fa-bell"></i><span>Alerts</span></a>
            <a href="#"><i class="fa fa-envelope"></i><span>Messages</span></a>
            <a href="#"><i class="fa fa-comment"></i><span>Comments</span></a>
        </div>
    </nav>
    <button class="close-button" id="close-button">Close Menu</button>
</div>

<!-- Search Form -->
<main class="page-content content-wrap">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="sidebar-pusher">
                <a href="javascript:void(0);" class="waves-effect waves-button waves-classic push-sidebar">
                    <i class="fa fa-bars"></i>
                </a>
            </div>
            <div class="logo-box">
                <a href="index.html" class="logo-text"><span>CMS</span></a>
            </div>
            <!-- Logo Box -->
            <div class="search-button">
                <a href="javascript:void(0);" class="waves-effect waves-button waves-classic show-search"><i
                        class="fa fa-search"></i></a>
            </div>
            <div class="topmenu-outer">
                <div class="top-menu">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="javascript:void(0);"
                               class="waves-effect waves-button waves-classic sidebar-toggle"><i class="fa fa-bars"></i></a>
                        </li>
                        <li>
                            <a href="#cd-nav" class="waves-effect waves-button waves-classic cd-nav-trigger"><i
                                    class="fa fa-diamond"></i></a>
                        </li>
                        <li>
                            <a href="javascript:void(0);"
                               class="waves-effect waves-button waves-classic toggle-fullscreen"><i
                                    class="fa fa-expand"></i></a>
                        </li>

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle waves-effect waves-button waves-classic"
                               data-toggle="dropdown">
                                <span class="user-name"><?php echo get('userFullName'); ?><i
                                        class="fa fa-angle-down"></i></span>
                                <img class="img-circle avatar"
                                     src="<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo get('userPhoto'); ?>"
                                     width="40" height="40" alt="">
                            </a>
                            <ul class="dropdown-menu dropdown-list" role="menu">
                                <li role="presentation"><a
                                        href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/Admin/Admin/Account"><i
                                            class="fa fa-user"></i>Profile</a></li>
                                <li role="presentation"><a href="calendar.html"><i
                                            class="fa fa-calendar"></i>Calendar</a></li>
                                <li role="presentation"><a href="inbox.html"><i class="fa fa-envelope"></i>Inbox<span
                                            class="badge badge-success pull-right">4</span></a></li>
                                <li role="presentation" class="divider"></li>
                                <li role="presentation"><a href="lock-screen.html"><i class="fa fa-lock"></i>Lock screen</a>
                                </li>
                                <li role="presentation"><a
                                        href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/Admin/Admin/Close"><i
                                            class="fa fa-sign-out m-r-xs"></i>Log out</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="<?PHP echo Com_Helper_Url::getInstance()->urlBase; ?>/Admin/Admin/Close"
                               class="log-out waves-effect waves-button waves-classic">
                                <span><i class="fa fa-sign-out m-r-xs"></i>Log out</span>
                            </a>
                        </li>

                    </ul>
                    <!-- Nav -->
                </div>
                <!-- Top Menu -->
            </div>
        </div>
    </div>
    <!-- Navbar -->
    <div class="page-sidebar sidebar">
        <div class="page-sidebar-inner slimscroll">
            <div class="sidebar-header">
                <div class="sidebar-profile">
                    <a href="javascript:void(0);" id="profile-menu-link">
                        <div class="sidebar-profile-image">
                            <img
                                src="<?PHP echo Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?php echo get('userPhoto'); ?>"
                                class="img-circle img-responsive" alt="">
                        </div>
                        <div class="sidebar-profile-details">
                            <span><?php echo get('userFullName'); ?><br></span>
                        </div>
                    </a>
                </div>
            </div>
            <ul class="menu accordion-menu">
                <a class="waves-effect waves-button" href="<?php echo Com_Helper_Url::getInstance()->urlBase.'/Admin/Admin'; ?>"> <span class="menu-icon glyphicon glyphicon-th-large"></span><p>Dashboard</p></a>
                <a class="waves-effect waves-button" href="<?php echo Com_Helper_Url::getInstance()->urlBase.'/Admin/Statistics'; ?>"> <span class="menu-icon glyphicon glyphicon-stats"></span><p>Estadísticas</p></a>
                <?PHP
                echo Com_Helper_Menu::getInstance();
                ?>
            </ul>
        </div>
        <!-- Page Sidebar Inner -->
    </div>
    <!-- Page Sidebar -->
    <div class="page-inner">
        <?php Com_Helper_Title::getInstance()->render(); ?>

        <div id="main-wrapper">

            <div class="row">
                <?PHP
                Com_Wizard_Messages::getInstance()->render();

                $this->getContent();
                ?>
            </div>
            <!-- Row -->

        </div>
        <!-- Main Wrapper -->
        <div class="page-footer">
            <p class="no-s">2015 &copy; Modern by Steelcoders.</p>
        </div>
    </div>
    <!-- Page Inner -->
</main>
<!-- Page Content -->
<nav class="cd-nav-container" id="cd-nav">
    <header>
        <h3>Navigation</h3>
        <a href="#0" class="cd-close-nav">Close</a>
    </header>
    <ul class="cd-nav list-unstyled">
        <li class="cd-selected" data-menu="index">
            <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-home"></i>
                        </span>

                <p>Dashboard</p>
            </a>
        </li>
        <li data-menu="profile">
            <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-user"></i>
                        </span>

                <p>Profile</p>
            </a>
        </li>
        <li data-menu="inbox">
            <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-envelope"></i>
                        </span>

                <p>Mailbox</p>
            </a>
        </li>
        <li data-menu="#">
            <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-tasks"></i>
                        </span>

                <p>Tasks</p>
            </a>
        </li>
        <li data-menu="#">
            <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-cog"></i>
                        </span>

                <p>Settings</p>
            </a>
        </li>
        <li data-menu="calendar">
            <a href="javsacript:void(0);">
                        <span>
                            <i class="glyphicon glyphicon-calendar"></i>
                        </span>

                <p>Calendar</p>
            </a>
        </li>
    </ul>
</nav>
<div class="cd-overlay"></div>


<!-- Javascripts -->

<?PHP
Com_Helper_Script::getInstance()
    ->addFile("Admin/jquery.min.js")
    ->addFile("Admin/jquery.ui.js")
    ->addFile("Admin/plugins/pace-master/pace.min.js")
    ->addFile("Admin/editor.js")
    ->addFile("Admin/datepicker.js")
    ->addFile("Admin/codemirror.js")
    ->addFile("Admin/codemirror.javascript.js")
    ->addFile("Admin/plugins/jquery-blockui/jquery.blockui.js")
    ->addFile("Admin/plugins/bootstrap/js/bootstrap.min.js")
    ->addFile("Admin/plugins/jquery-slimscroll/jquery.slimscroll.min.js")
    ->addFile("Admin/plugins/switchery/switchery.min.js")
    ->addFile("Admin/plugins/uniform/jquery.uniform.min.js")
    ->addFile("Admin/plugins/offcanvasmenueffects/js/classie.js")
    ->addFile("Admin/plugins/offcanvasmenueffects/js/main.js")
    ->addFile("Admin/codemirror.javascript.js")
    ->addFile("Admin/plugins/waves/waves.min.js")
    ->addFile("Admin/plugins/3d-bold-navigation/js/main.js")
    ->addFile("Admin/plugins/waypoints/jquery.waypoints.min.js")
    ->addFile("Admin/plugins/jquery-counterup/jquery.counterup.min.js")
    ->addFile("Admin/plugins/toastr/toastr.min.js")
//    ->addFile("Admin/plugins/flot/jquery.flot.min.js")
//    ->addFile("Admin/plugins/flot/jquery.flot.time.min.js")
//    ->addFile("Admin/plugins/flot/jquery.flot.symbol.min.js")
//    ->addFile("Admin/plugins/flot/jquery.flot.resize.min.js")
//    ->addFile("Admin/plugins/flot/jquery.flot.tooltip.min.js")
//    ->addFile("Admin/plugins/curvedlines/curvedLines.js")
    ->addFile("Admin/plugins/metrojs/MetroJs.js")
    ->addFile("Admin/modern.js")

//    ->addFile("Admin/pages/dashboard.js")
    ->addFile("Admin/admin.js")
    ;

echo Com_Helper_Script::getInstance();
?>

</body>
</html>