<?PHP

$db = new Entities_Tool();
$grid = new Com_Wizard_Grid();
$grid->title = "Listado Tools ";
$grid->setIdField("TooId");
$grid->setLanField("TooLanId");
$grid->setQuery($db->getListWithLanguages());
$grid->setAlias(array("LanName" => "Idioma", "TooName" => "Nombre","TooType" => "Tipo", "TooStatus" => "Estado"));
$grid->setFilters(array("TooName" => get('TooName')));

$toolBar = new Com_Wizard_ToolBar();
$toolBar->add("plus", "Nuevo", Com_Helper_Url::getInstance()->urlBase . '/Admin/Tools/Add');
$toolBar->add("search", "Filtrar", null, "showHide('.filters')");
$toolBar->add("log-out", "Volver", Com_Helper_Url::getInstance()->urlBase . '/Admin');
$grid->setToolBar($toolBar);

$grid->addAction("pencil", "Editar", Com_Helper_Url::getInstance()->urlBase . '/Admin/Tools/Edit/lan/_LANGUAGE_/id/_ID_');
$grid->addAction("trash", "Eliminar", null, "confirm('Esta seguro de eliminar el registro?')?location.href='" . Com_Helper_Url::getInstance()->urlBase . '/Admin/Tools/Delete/id/_ID_' . "':'';");

$grid->customField("TooStatus", array("value" => array('1' => 'Habilitado', '0' => 'Bloqueado')));

$grid->render();
