<section class="col-xs-12">

    <div class="container-fluid content-header-1">
        <div class="row">
            <!--    poner clase bg-note-$color        -->
            <div class="col-sm-12 content-header-1-title bg-bookmall">
                <h3>BookMall</h3>
            </div>
        </div>
    </div>
    <section>
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <?php SlideShows_Widget_Slideshow::getInstance()->setLan($this->lan)->render(); ?>
            </div>
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets"></div>
        </div>
    </section>
    <div class="container-fluid content-tool notas-items">
        <div class="row">
            <div class="col-sm-6 col-md-4 notas-item">
                <div class="square"
                     style="background-image:url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50911.jpg);background-size:cover ">
                    <div class="square square-hover bg-white">

                        <div class="content">
                            <a href="#">
                                <h3>titulo</h3>
                            </a>
                            <p>
                                This Monday we're bringing you the Spooky Halloween Stamps Brush Set! We made some
                                spooky Halloween stamps for you to help make your drawings slightly more sinister. This
                                set has a bunch of stamps you can use to quickly add classic forms for Halloween: Jack
                                ‘o Lanterns, Spider Eggs, Scratch Marks, and more.

                                <a href="#" class="tag bg-tag-bookmall">
                                    <span>ver mas</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <h3>Titulo
                        <small class="tag bg-tag-bookmall pull-right"> comprar</small>
                    </h3>
                </a>
            </div>
            <div class="col-sm-6 col-md-4 notas-item">
                <div class="square"
                     style="background-image:url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50911.jpg);background-size:cover ">
                    <div class="square square-hover bg-white">

                        <div class="content">
                            <a href="#">
                                <h3>titulo</h3>
                            </a>
                            <p>
                                This Monday we're bringing you the Spooky Halloween Stamps Brush Set! We made some
                                spooky Halloween stamps for you to help make your drawings slightly more sinister. This
                                set has a bunch of stamps you can use to quickly add classic forms for Halloween: Jack
                                ‘o Lanterns, Spider Eggs, Scratch Marks, and more.

                                <a href="#" class="tag bg-tag-bookmall">
                                    <span>ver mas</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <h3>Titulo
                        <small class="tag bg-tag-bookmall pull-right"> comprar</small>
                    </h3>
                </a>
            </div>
            <div class="col-sm-6 col-md-4 notas-item">
                <div class="square"
                     style="background-image:url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50911.jpg);background-size:cover ">
                    <div class="square square-hover bg-white">

                        <div class="content">
                            <a href="#">
                                <h3>titulo</h3>
                            </a>
                            <p>
                                This Monday we're bringing you the Spooky Halloween Stamps Brush Set! We made some
                                spooky Halloween stamps for you to help make your drawings slightly more sinister. This
                                set has a bunch of stamps you can use to quickly add classic forms for Halloween: Jack
                                ‘o Lanterns, Spider Eggs, Scratch Marks, and more.

                                <a href="#" class="tag bg-tag-bookmall">
                                    <span>ver mas</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <h3>Titulo
                        <small class="tag bg-tag-bookmall pull-right"> comprar</small>
                    </h3>
                </a>
            </div>
            <div class="col-sm-6 col-md-4 notas-item">
                <div class="square"
                     style="background-image:url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50911.jpg);background-size:cover ">
                    <div class="square square-hover bg-white">

                        <div class="content">
                            <a href="#">
                                <h3>titulo</h3>
                            </a>
                            <p>
                                This Monday we're bringing you the Spooky Halloween Stamps Brush Set! We made some
                                spooky Halloween stamps for you to help make your drawings slightly more sinister. This
                                set has a bunch of stamps you can use to quickly add classic forms for Halloween: Jack
                                ‘o Lanterns, Spider Eggs, Scratch Marks, and more.

                                <a href="#" class="tag bg-tag-bookmall">
                                    <span>ver mas</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <h3>Titulo
                        <small class="tag bg-tag-bookmall pull-right"> comprar</small>
                    </h3>
                </a>
            </div>
            <div class="col-sm-6 col-md-4 notas-item">
                <div class="square"
                     style="background-image:url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50911.jpg);background-size:cover ">
                    <div class="square square-hover bg-white">

                        <div class="content">
                            <a href="#">
                                <h3>titulo</h3>
                            </a>
                            <p>
                                This Monday we're bringing you the Spooky Halloween Stamps Brush Set! We made some
                                spooky Halloween stamps for you to help make your drawings slightly more sinister. This
                                set has a bunch of stamps you can use to quickly add classic forms for Halloween: Jack
                                ‘o Lanterns, Spider Eggs, Scratch Marks, and more.

                                <a href="#" class="tag bg-tag-bookmall">
                                    <span>ver mas</span>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <h3>Titulo
                        <small class="tag bg-tag-bookmall pull-right"> comprar</small>
                    </h3>
                </a>
            </div>


        </div>
    </div>
</section>

<section class="col-xs-12">
    <div class="container-fluid">
        <div class="row bg-white bookmall-detail">
            <div class="col-sm-6">
                <div id="book-image" class="square"
                     style="background-image:url(http://blogdesuperheroes.es/wp-content/plugins/BdSGallery/BdSGaleria/50911.jpg);background-size:cover ">
                </div>
                <section class="insta-wrap">

                    <div data-instafeed-clientid="44f19408f04040bd85214315861a84a1" data-instafeed-get="user"
                         data-instafeed-user="499522078" data-items="2" data-sm-items="3" data-lg-items="4"
                         data-loop="true"
                         data-nav="true" class="owl-carousel element-groups-xs-custom">
                        <div data-instafeed-item="" class="owl-item insta-item">
                            <a href="javascript:void(0)"
                               id="thumb-1"
                               rel="https://cdn2.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-kickstand.jpg"
                               onclick="setImage(1)"
                               class="img-thumbnail-variant-3">
                                <div class="square"
                                     style="background: url(https://cdn2.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-kickstand.jpg); background-size: cover">
                                </div>
                            </a>
                        </div>
                        <div data-instafeed-item="" class="owl-item insta-item">
                            <a href="javascript:void(0)"
                               id="thumb-2"
                               rel="https://cdn1.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-mockup_thumb800.jpg"
                               onclick="setImage(2)"
                               class="img-thumbnail-variant-3">
                                <div class="square"
                                     style="background: url(https://cdn1.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-mockup_thumb800.jpg); background-size: cover">
                                </div>
                            </a>
                        </div>
                        <div data-instafeed-item="" class="owl-item insta-item">
                            <a href="#"
                               rel="group" <?= !empty($new->GalName) ? 'title="' . $new->GalName . '"' : "" ?>
                               class="img-thumbnail-variant-3">
                                <div class="square"
                                     style="background: url(https://cdn2.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-kickstand.jpg); background-size: cover">
                                </div>
                            </a>
                        </div>
                        <div data-instafeed-item="" class="owl-item insta-item">
                            <a href="<?= Com_Helper_Url::getInstance()->getUploads(); ?>/Image/<?PHP echo $new->GalFile; ?>"
                               rel="group" <?= !empty($new->GalName) ? 'title="' . $new->GalName . '"' : "" ?>
                               class="img-thumbnail-variant-3">
                                <div class="square"
                                     style="background: url(https://cdn1.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-mockup_thumb800.jpg); background-size: cover">
                                </div>
                            </a>
                        </div>
                        <div data-instafeed-item="" class="owl-item insta-item">
                            <a href="#"
                               rel="group"
                               class="img-thumbnail-variant-3">
                                <div class="square"
                                     style="background: url(https://cdn2.pcadvisor.co.uk/cmsdata/features/3627431/surface-phone-rumours-kickstand.jpg); background-size: cover">
                                </div>
                            </a>
                        </div>
                        <script>
                            setImage = function (id) {
                                var url = $("#thumb-" + id).attr("rel")
                                console.log(this);
                                $('#book-image').css('background-image', 'url(' + url + ')');
                            }
                        </script>
                        <!--                        incluir este script en el widget-->
                    </div>
                </section>
            </div>
            <div class="col-sm-6">
                <h4>Lorem ipsum dolor sit amet</h4>
                <p class="bookmall-autor">AUTOR: <strong>Lorem ipsum dolor</strong></p>
                <p>
                    While most women go right after lipsticks or chase over foundations, my personal beauty obsession
                    has got to be products for my face and specifically cheeks: blushes, bronzers, creams, powders, your
                    skin and features to be even brighter. The perfect shade of blush will bring out the best in your
                    style and conceal any imperfections and, even if you don`t have a scrap of any other product on, it
                    will bring your skin to a healthier state than before <br>

                </p>

                <ul>
                    <li><strong>Tamano:</strong> Lorem ipsum dolor</li>
                    <li><strong>Hojas:</strong> Lorem ipsum dolor</li>
                    <li><strong>Autor:</strong> Lorem ipsum dolor</li>
                    <li><strong>Sitio web:</strong> Lorem ipsum dolor</li>
                </ul>

                <div class="pull-right" style="clear: both;margin: 10px 0">PRECIO: <strong
                        class="color-purple">$9999</strong></div>

                <div class="pull-right" style="clear: both;margin: 10px 0">
                    <ul class="list-inline">
                        <li>
                            <a target="_blank" href="http://www.facebook.com/sharer.php?u=[post-url]"
                               class="icon icon-md icon-gray fa fa-facebook"></a>
                        </li>
                        <li>
                            <a target="_blank"
                               href="https://twitter.com/share?url=[post-url]&text=[post-title]&via=[via]&hashtags=[hashtags]"
                               class="icon icon-md icon-gray fa fa-twitter"></a>
                        </li>
                        <li>
                            <a target="_blank" href="https://plus.google.com/share?url=[post-url]"
                               class="icon icon-md icon-gray fa fa-google-plus"></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-12" style="height: 2px; background: #999999"></div>
            <div class="col-md-12">
                <a href="#" class="btn btn-flat pull-right btn-yellow">Comprar</a>
                <a href="#" class="btn btn-flat pull-right btn-primary" style="margin-right: 10px">Aniadir carrito</a>
            </div>
        </div>
    </div>
    <!--    aqui deberia empezar el widget de carrito-->
    <div class="container-fluid carrito bg-white">
        <div class="row">
            <form action="#" method="post">
                <div class="col-md-6">
                    <h3>Detalle de compra</h3>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="nombre">Nombre completo</label>
                                <input type="text" class="form-control" id="nombre" placeholder="nombre">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="apellido">Apellido completo</label>
                                <input type="text" class="form-control" id="apellido" placeholder="apellido">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="cedula">Cedula</label>
                        <input type="text" class="form-control" id="cedula" placeholder="cedula">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Direccion de email</label>
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Celular</label>
                                <input type="text" class="form-control" id="celular" placeholder="celular">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pais">Pais</label>
                        <input type="text" class="form-control" id="pais" placeholder="pais">
                    </div>
                    <div class="form-group">
                        <label for="direccion">Direccion</label>
                        <input type="text" class="form-control" id="direccion1" placeholder="direccion 1">
                        <input type="text" class="form-control" id="direccion2" placeholder="direccion 2">
                    </div>
                    <div class="form-group">
                        <label for="localidad">Localidad/Ciudad</label>
                        <input type="text" class="form-control" id="localidad" placeholder="localidad">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Estado / Pais</label>
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Codigo postal / Zip</label>
                                <input type="text" class="form-control" id="celular" placeholder="celular">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <h3>Detalle de compra</h3>
                    <div class="form-group">
                        <label for="direccion">Direccion</label>
                        <input type="text" class="form-control" id="direccion1" placeholder="direccion 1">
                        <input type="text" class="form-control" id="direccion2" placeholder="direccion 2">
                    </div>
                    <div class="form-group">
                        <label for="localidad">Localidad/Ciudad</label>
                        <input type="text" class="form-control" id="localidad" placeholder="localidad">
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="email">Estado / Pais</label>
                                <input type="text" class="form-control" id="email" placeholder="email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="celular">Codigo postal / Zip</label>
                                <input type="text" class="form-control" id="celular" placeholder="celular">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripcion</label>
                        <input type="text" class="form-control" id="descripcion" placeholder="descripcion">
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
